### ISSUE TITLE
Separate Video Roles & Audio Roles Column in CSV

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#1]
In the current built, Both **Video Roles** and **Audio Roles** are listed in `Role & Subrole` column.

In the next build, **Video Roles** will be listed in `Video Role & Subrole` column. And **Audio Roles** will be listed in `Audio Role & Subrole` column.

**Comment by orchetect** [comment]
I've now implemented this.

Since I'm not an expert with FCP, is it possible to have more than one role? I'm only asking because the code internally is searching multiple layers of data to find roles.

**Comment by IAmVigneswaran** [comment]
There can be more than 1 video role and and more the 1 audio role. The default for the **videos roles** are `Title` and `Video`.  And the default for the **audio roles** are `Dialogue`, `Effects` and `Music`. Users can create as many custom roles as they like.

<img width="547" alt="Roles" src="https://user-images.githubusercontent.com/118706051/210045140-93d84ac5-7d2f-48fc-91da-f05de7666f03.png">

**Comment by orchetect** [comment]
I know that. I'm asking if a single marker can have more than one role.

**Comment by IAmVigneswaran** [comment]
> I know that. I'm asking if a single marker can have more than one role.

A single marker does not have a role. It can be unanimously placed on any clip (video or audio) regardless of their role.

**Comment by orchetect** [comment]
Right, it inherits the role of the clip it's attached to.

And a roles can have subroles. But I think that's as deep as it goes for a single "role" assignment to any clip.

But I wonder if there is a possibility by inheritance, perhaps with compound clips or some advanced feature of FCP - is there a scenario where a clip (ergo, a marker) could receive more than one role if layers above it have different roles? Or should we expect that there can only be a single role for a clip?

**Comment by IAmVigneswaran** [comment]
> Right, it inherits the role of the clip it's attached to.

Yes.

> And a roles can have subroles. But I think that's as deep as it goes for a single "role" assignment to any clip.

Yes, there is only 1 level of subrole.

> But I wonder if there is a possibility by inheritance, perhaps with compound clips or some advanced feature of FCP - is there a scenario where a clip (ergo, a marker) could receive more than one role if layers above it have different roles? Or should we expect that there can only be a single role for a clip?

When there are compound clips, multicam clips or synchronised clips, markers can be places within them in all places. And users on the main timeline can place markers on top of compound clips, multicam clips or synchronised clips. Our tool should always only look at and parse the markers on the **main timeline**. It should ignore all the rest. Which brings to this [issue](https://github.com/TheAcharya/MarkersExtractor/issues/7).

> Or rather, should we only look for a marker's role from the clip it's attached to?

To word it another way, we should parse for the roles of the clip (Video or Audio) that the Markers are attached too. Since "Technically" within FCP Markers don't have roles.

**Comment by orchetect** [comment]
Great - that makes sense.

> Is this optimal or would you like a single column for the role name as before, but an additional column for the role type ("Audio" or "Video")?

Just circling back to this. Do you like the Video column + Audio column? Or would you prefer this option?

**Comment by IAmVigneswaran** [comment]
> Just circling back to this. Do you like the Video column + Audio column? Or would you prefer this option?

Do do mean having an option in CLI to combine both `Video` and `Audio` column? 

Having options are great for the end users. In this instance, I feel there is no need for such an option. Both `Video` and `Audio` column will all always be its own separate column.

Cause from a database point of view, users will always have more flexibility in filtering or creating search criteria when `Video` and `Audio` are columns separate. User will further have the ability to show/hide columns in Notion or Airtable.

Not sure if I have answered your question.  Your current iteration is perfect!

<details>
<summary>Screenshot</summary>

![](https://user-images.githubusercontent.com/11605557/210045565-a070f7f3-f4e1-41a5-83b8-b3467b95aecd.png)
</details>

**Comment by orchetect** [comment]
> Do do mean having an option in CLI to combine both `Video` and `Audio` column?

Yes, this is what I was describing:

<img width="267" alt="role-roletype" src="https://user-images.githubusercontent.com/11605557/210123025-fae78496-6cff-489b-9eb3-1c26a2aee0d9.png">

> Your current iteration is perfect!

Ok we can leave as-is.
