### ISSUE TITLE
24 hours format timestamp in folder name.

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#100]
@orchetect For the folder name, can the timestamp be in 24 hours format?

Thank you.

**Comment by orchetect** [comment]
Which timestamp? Is it not using timecode?

**Comment by IAmVigneswaran** [comment]
> Which timestamp? Is it not using timecode?

My bad. I mean the folder name.

<img width="393" alt="Folder Name Timestamp" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/b8001fbf-209a-4c32-8ee9-6cc61fc7d65b">

**Comment by orchetect** [comment]
Yeah no problem, was probably an oversight originally.
