### ISSUE TITLE
Profiles & Formats (Pro Tools)

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#104]
@orchetect Does it make sense to add a compatible Pro Tools export profile?

Pro Tools allows users to export `Session Info as Text`.

<details><summary>Session Info as Text</summary>

![](https://editingtools.io/marker/assets/protools_export.png)

</details>

There is also a third-party app called EditMarker for Pro Tools.

https://www.soundsinsync.com/products/edimarker

I believe it can import and convert the text file as Pro Tools's `.ptx`.

**Comment by orchetect** [comment]
No, there's already been a Pro Tools thread. Session Text is export only. Importing back into PT is really only feasible by MIDI. The ptx file format is encrypted and proprietary.

**Comment by IAmVigneswaran** [comment]
> No, there's already been a Pro Tools thread.

Opps! My bad.
