### ISSUE TITLE
Compatibility with FCPXML 1.12

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#106]
@orchetect Apple have updated FCPXML to 1.12 in the last release of FCP 10.8.

FCPXML v1.12 only have a few new additions:

- Added `<!ATTLIST filter-video nameOverride CDATA #IMPLIED>`
- Added `<!ATTLIST filter-audio nameOverride CDATA #IMPLIED>`
- Updated `<!ATTLIST conform-rate frameSampling (floor | nearest-neighbor | frame-blending | optical-flow-classic | optical-flow | optical-flow-frc) "floor">`
- Updated `<!ATTLIST timeMap frameSampling (floor | nearest-neighbor | frame-blending | optical-flow-classic | optical-flow | optical-flow-frc) "floor">`
- Updated `<!ATTLIST match-text rule (includes | doesNotInclude | is | isNot | startsWith | endsWith) "includes">`
- Updated `<!ATTLIST match-property rule (includes | doesNotInclude | is | isNot | isSet | isNotSet | startsWith | endsWith) "includes">`

Source:
https://fcp.cafe/news/20240621/

I am wondering if any update is required to your  DAWFileKit? Particularly `conform-rate` or `timeMap`?
I did some basic test with Marker Data and MarkersExtractor CLI, I did not encounter any issues so far.

[FCPXMLv1_12.dtd.zip](https://github.com/user-attachments/files/15934696/FCPXMLv1_12.dtd.zip)

**Comment by orchetect** [comment]
DAWFileKit is updated. Nothing is affected for our use.
