### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#11]
Unit tests need to be written to ensure correctness of data parsing and prevent future regressions.

It will also save a lot of time by automating logic testing so that manual testing can be kept to a minimum as new features are added and bugs get fixed.

**Comment by orchetect** [comment]
Since most of the parsing is now happening in DAWFileKit, I have been incrementally unit-testing the parsing logic in DAWFileKit.

I am also adding tests to MarkersExtractor as needed, and hopefully more as time goes on.

**Comment by IAmVigneswaran** [comment]
Can we close this?
