### ISSUE TITLE
New Frame Rates Added in Final Cut Pro 11

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#112]
@orchetect 

Continuing discussion from #81

In the latest version of FCP 11, Apple have added support for 3 additional Frame Rates `90`, `100` and `120`.

<img width="631" alt="FCP 11 - Frame Rates" src="https://github.com/user-attachments/assets/ae963baf-2ce4-47a1-a740-261eaf4487c0">

Hopefully we can support them in future builds of MarkersExtractor.

**Comment by orchetect** [comment]
100 and 120 is already supported

**Comment by orchetect** [comment]
TimecodeKit is updated: https://github.com/orchetect/TimecodeKit/releases/tag/2.3.3

**Comment by orchetect** [comment]
DAWFileKit doesn't need updating to take advantage of the new 90 fps rate. The TimecodeKit release handles it.

**Comment by IAmVigneswaran** [comment]
Noted!

**Comment by orchetect** [comment]
0.3.12 Released: https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.12

**Comment by IAmVigneswaran** [comment]
> 0.3.12 Released: https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.12

Marker Data 1.1.1 Released https://github.com/TheAcharya/MarkerData/releases/tag/v1.1.1

Thank you!
