### ISSUE TITLE
Compatibility with FCPXML 1.13

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#113]
@orchetect 

With the release of Final Cut Pro 11, there is a new version of FCPXML 1.13. 

These are the difference that I found when comparing with FCPXML 1.12's DTDs.

```
<!ATTLIST format heroEye CDATA #IMPLIED>			<!-- ("left" | "right") -->
<!ATTLIST asset heroEyeOverride CDATA #IMPLIED>		<!-- ("left" | "right") -->

<!ELEMENT adjust-stereo-3D (param*)>
<!ATTLIST adjust-stereo-3D enabled (0 | 1) "1">
<!ATTLIST adjust-stereo-3D convergence CDATA "0">
<!ATTLIST adjust-stereo-3D autoScale (0 | 1) "1">
<!ATTLIST adjust-stereo-3D swapEyes (0 | 1) "0">
<!ATTLIST adjust-stereo-3D depth CDATA "0">


<!ENTITY % intrinsic-params-video "(object-tracker?, adjust-crop?, adjust-corners?, adjust-conform?, adjust-transform?, adjust-blend?, adjust-stabilization?, adjust-rollingShutter?, adjust-360-transform?, adjust-reorient?, adjust-orientation?, adjust-cinematic?, adjust-colorConform?, adjust-stereo-3D?)">

<!ENTITY % intrinsic-params-live-drawing "adjust-crop?, adjust-corners?, adjust-conform?, adjust-transform?, adjust-blend?, adjust-360-transform?, adjust-colorConform?, adjust-stereo-3D?">

<!ENTITY % marker_item "(marker | chapter-marker | rating | keyword | analysis-marker | hidden-clip-marker)">

<!ATTLIST spine %ao_attrs;>

<!ATTLIST conform-rate srcFrameRate (23.98 | 24 | 25 | 29.97 | 30 | 60 | 47.95 | 48 | 50 | 59.94 | 90 | 100 | 119.88 | 120) #IMPLIED>

<!ELEMENT hidden-clip-marker EMPTY>

```

[Final_Cut_Pro_XML_DTD_version_1.13.dtd.zip](https://github.com/user-attachments/files/17742178/Final_Cut_Pro_XML_DTD_version_1.13.dtd.zip)

I believe you might have to update your DAWFileKit? 

MarkersExtractor is pretty much unaffected by the new changes except for the new frame rates?

You mention, that 100 and 120 is already supported?

**Comment by orchetect** [comment]
The only pertinent changes are these:

```diff
- <!ENTITY % marker_item "(marker | chapter-marker | rating | keyword | analysis-marker)">
+ <!ENTITY % marker_item "(marker | chapter-marker | rating | keyword | analysis-marker | hidden-clip-marker)">
```

```diff
+ <!ELEMENT hidden-clip-marker EMPTY>
```

Apple added what looks like new marker type (Hidden Clip Marker), however it doesn't contain any data.

It seems related to this new feature in Final Cut Pro 11.0:

- [Hide clips in the browser in Final Cut Pro for Mac](https://support.apple.com/en-ca/guide/final-cut-pro/verf02db6a29/11.0/mac/15.1)

After some investigating, it looks like it's used as a flag to indicate a clip is hidden. It's not actually a marker at all.

The only new information this gives us is whether a clip is hidden in a user's clip browser.

In testing, I was not able to find the flag in a project FCPXML that was exported that used a hidden clip.

However, it does show up when the clip itself is exported from the browser as FCPXML:

```xml
<library location="file:///Users/user/Movies/FCPXMLTest.fcpbundle/">
        <event name="Test Event" uid="BB995477-20D4-45DF-9204-1B1AA44BE054">
            <ref-clip ref="r1" name="My Hidden Clip" duration="24100/2400s" modDate="2024-11-14 00:37:45 -0800">
                <hidden-clip-marker/>
            </ref-clip>
        </event>
</library>
```

Seems safe to ignore for now - there's no real value to parsing it.

**Comment by orchetect** [comment]
> 100 and 120 is already supported

100 and 120 fps were implemented quite a while ago, and 90 was just added today. See #112

**Comment by IAmVigneswaran** [comment]
> 119.88 was also slipped into the FCPXML 1.13 DTD, although I don't actually see it as an option in a new Custom project in FCP. Either way, that's also been implemented for a while already as well.

Interesting! Maybe FCP interprets or interpolates 119.8 as 120?

Thanks for updating TimecodeKit!

**Comment by orchetect** [comment]
> Maybe FCP interprets or interpolates 119.88 as 120

No, it's a completely different frame rate. It's 2 x 59.94.

**Comment by IAmVigneswaran** [comment]
> No, it's a completely different frame rate. It's 2 x 59.94.

Ah! Noted!

**Comment by orchetect** [comment]
0.3.12 Released: https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.12
