### ISSUE TITLE
Ability to hide label IDs overlaid on thumbnail images

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#16]
Currently thumbnail image labels include both the label name and the label value:

![29 97_V1_00_00_11_23](https://user-images.githubusercontent.com/11605557/209747850-922d3d3d-e26c-47af-9a96-26d127965384.png)

For some users the label names may be redundant and make the labels occupy more area of the image than they may need.

- [x] Add a CLI flag `--label-hide-names` to hide the name of them label and only use the label value.

**Comment by orchetect** [comment]
Implemented on the refactors branch.

![29 97_V1_00_00_11_23](https://user-images.githubusercontent.com/11605557/209749051-a2952f6d-21bf-45d9-8ee6-f31589456db7.png)

**Comment by IAmVigneswaran** [comment]
Awesome!
