### ISSUE TITLE
Ability to render marker icon on image thumbnail

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#19]
Optionally, it would be a cool feature to render the marker's icon on image thumbnails. Perhaps in one of the image's corners or inline with the label text, treating the icon simply as another label type.

It could help visually differentiate between marker types as well.

**Comment by IAmVigneswaran** [comment]
The marker icon is design for [Notion in mind](https://www.notion.so/help/guides/page-icons-and-covers). And [csv2notion](https://github.com/vzhd1701/csv2notion) supports direct upload of Marker Icons to Notion. 

The current implementation of of the CLI auto generates marker icons based on the FCP's Marker types. I believe they are hardcoded. And I would like that to be the default mode.

But I like the idea custom icons based on the video's image. Users could identify each data entry visually. It is cool!

If we are taking Notion into consideration, there is already a Gallery View where each record be identified by still or GIFs. In [Table view](https://www.notion.so/help/tables), the icons are very small. Hence, I am not sure having custom icons based on the video's image would be meaningful to the user. 

Airtable does not support icons for its records.

If any user request this feature for their workflow, we can implement it down the line?

**Comment by orchetect** [comment]
Sure, we can back-burner it and circle back when/if it feels appropriate.

What prompted me to come up with the idea is that depending on the CLI options, maker names may show up as label text on the image thumbnail but there isn't always a clear way to tell what marker type it is. Sure, the marker type label could be shown but since we already have the icon graphics assets it would be more pleasing to use those.

**Comment by IAmVigneswaran** [comment]
We can add this feature in future if any workflow or user requests for it. :)

**Comment by IAmVigneswaran** [comment]
FYI, A notion user have mange to convert, upload the entire Shrek movie in a GIF and upload it as aNotion icon.

https://whoibrar.notion.site/Entire-Shrek-Movie-as-Notion-Icon-d9a0eef877864dcf99f4c5da5fb32ce4
