### ISSUE TITLE
Issues with 0.2.0-alpha-20221230.0

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#30]
@orchetect I am getting some errors when I try using the new build. Am I doing anything wrong?

My .sh script.

```
#!/bin/sh

TOOL_PATH="/Users/xxx/Desktop/Marker_Data/App/0.2.0/markers-extractor-cli"
FCPXML_PATH="/Users/xxx/Desktop/Marker_Data/App/0.2.0/Render/Marker Data Demo_V1.fcpxmld"
OUTPUT_DIR="/Users/xxx/Desktop/Marker_Data/App/0.2.0/Output"
ERROR_LOG="/Users/xxx/Desktop/Marker_Data/App/0.2.0/log.txt"

$TOOL_PATH "$FCPXML_PATH" "$OUTPUT_DIR" --export-format csv2notion --log-level debug --log $ERROR_LOG
```

Error

```
WARNING: Marker at 00:03:45:03 is out of bounds of its parent clip.
MarkersExtractor/resource_bundle_accessor.swift:40: Fatal error: unable to find bundle named MarkersExtractor_MarkersExtractor
/Users/xxx/Desktop/Marker_Data/App/0.2.0/Tester_still.sh: line 8:  2460 Illegal instruction: 4  $TOOL_PATH "$FCPXML_PATH" "$OUTPUT_DIR" --export-format csv2notion --log-level debug --log $ERROR_LOG
```

I am able to process the same FCPXML with the previous 0.1.1 build without any errors.

**Comment by orchetect** [comment]
Thanks for the heads-up, I found the source of the bug.

**Comment by IAmVigneswaran** [comment]
Side note - For `--log-level <trace,debug,info,notice,warning,error,critical>`. What is the difference between `trace` and `debug`? Which should I use for error reporting?

**Comment by orchetect** [comment]
Fixed. New alpha build is up:

https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.2.0-alpha-20221231.0

**Comment by orchetect** [comment]
> What is the difference between trace and debug? Which should I use for error reporting?

`debug` is adequate for error reporting.

**Comment by IAmVigneswaran** [comment]
Thanks works for now. Will close this for now.
