### ISSUE TITLE
Add Progress Reporting

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#31]
@orchetect Can we add a Progress Bar in the CLI before it shows "Done!"

Something similar to this?

https://github.com/jkandzi/Progress.swift
https://www.npmjs.com/package/cli-progress

**Comment by orchetect** [comment]
Won't make it into 0.2.0 but it may be possible as long as it doesn't interfere with outputting warning messages during the process.

**Comment by IAmVigneswaran** [comment]
> Won't make it into 0.2.0 but it may be possible as long as it doesn't interfere with outputting warning messages during the process.

Noted! But it might be useful for the GUI app. In CommandPost Toolbox, Chris might be able to read the Progress Bar and embed it into the GUI.

**Comment by orchetect** [comment]
> In CommandPost Toolbox, Chris might be able to read the Progress Bar and embed it into the GUI.

@latenitefilms I'm not totally sure this is possible. Any suggestions?

**Comment by latenitefilms** [comment]
We'll just be triggering it via a `NSTask`, so we can read anything that spits out of `stdout` and `stderr`.

**Comment by theogscott** [comment]
If progress needs to be reported to the, and stdout won't help in a GUI environment. Maybe have a callback?

**Comment by orchetect** [comment]
The library can either provide a simple callback, or conform to [`ProgressReporting`](https://developer.apple.com/documentation/foundation/progressreporting) which would provide a [`Progress`](https://developer.apple.com/documentation/foundation/progress) instance.

As for CLI progress, it's also possible to emit running progress to `stdout`. Whether it simply outputs progress lines, or manipulates console control characters to have status continually fixed to the end of the output is another question.

**Comment by orchetect** [comment]
Currently doing refactors necessary to enable progress reporting both through the library (by way of `ProgressReporting`) and the CLI (as console output).

Doing so is requiring refactoring the library to support concurrency (multithreading). See:
- #49

**Comment by IAmVigneswaran** [comment]
@milanvarady as suggested by Steffan, I believe you can tap/read and integrate Marker Data's Progress bar by utilising the above.

**Comment by orchetect** [comment]
Barebones progress reporting is implemented now.

It outputs basic overall progress but isn't showing granular per-thumbnail progress just yet. Although, with the latest performance improvements with concurrency it may be far less important now. But it will still be useful for very large marker sets which could take time to process, so I will revisit this soon.

**Comment by orchetect** [comment]
Progress reporting both through CLI and library API is now fully implemented and tested.

Will be in the next release (0.2.2).

**Comment by orchetect** [comment]
As a side note: the current CLI console output for progress is fairly rudimentary and not as pretty as progress bars shown in the linked repos.

That could be improved in future, however it's not quite as trivial as strapping on a 3rd-party package in our case. It would be a tricky refactor due to how logging is performed.

**Comment by IAmVigneswaran** [comment]
> As a side note: the current CLI console output for progress is fairly rudimentary and not as pretty as progress bars shown in the linked repos.

Yes, not a big issue. @milanvarady I believe if we are able to tap and read the values for our GUI's Progress bar, it would accomplish the task.
