### ISSUE TITLE
Add the option to use FCP thumbnail frame for Chapter markers

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#32]
## Background

In Final Cut Pro, the chapter marker allows you to set an independent thumbnail image for the marker. This is adjusted by the user as an offset from the marker's location because it's attached to the marker as a visual aid. It can be earlier or later in the timeline than the marker's location. The absolute location of this secondary is intended to be used for thumbnail generation of chapter markers, as one would intuit from FCP's user interface and the tooltip help text.

Later on the timeline:
<img width="486" alt="chapter-thumb-pin" src="https://user-images.githubusercontent.com/11605557/210191691-d33ac108-fce2-40c1-acd6-d0079b32645e.png">

Earlier on the timeline:
<img width="337" alt="chapter-thumb-pin-2" src="https://user-images.githubusercontent.com/11605557/210191897-fcfb2f74-cee0-4679-9da3-bad65aeed238.png">

## Current Behavior

Currently, this secondary chapter marker thumbnail pin location is ignored and not used at all in MarkersExtractor.

## Proposal

It would seem beneficial to add a CLI flag like `--use-chapter-marker-thumbnails` to have thumbnail images for chapter 
markers use this secondary time as the basis for its thumbnail generation instead of the marker's location.

## Considerations

Of course, this would only affect thumbnail images. The output (CSV) would still contain the marker's location. However this may be a little confusing when using `projectTimecode` (default) naming mode because the marker ID will contain timecode that does not match the video frame that appears in chapter markers' image thumbnails.

**Comment by IAmVigneswaran** [comment]
> It would seem beneficial to add a CLI flag like --use-chapter-marker-thumbnails to have thumbnail images for chapter
> markers use this secondary time as the basis for its thumbnail generation instead of the marker's location.

> Of course, this would only affect thumbnail images. The output (CSV) would still contain the marker's location. However this may be a little confusing when using projectTimecode (default) naming mode because the marker ID will contain timecode that does not match the video frame that appears in chapter markers' image thumbnails.

I have thought about this, but to prevent confusion, I did not propose this feature. Since it would match video frame thumbnails.

What are your thoughts?

**Comment by orchetect** [comment]
I'm not fully aware of how FCP uses this feature itself, or how it intends on it to be used.

There must be FCP workflows that use the custom thumbnail frames.

To that end, I would probably defer to your opinion.

Perhaps if we have an option to enable this, any thumb images we generate for chapter markers could also include a special "Thumb Timecode" label imprint noting the image's timecode, like this:

```
Marker Position: 00:00:04:12
Thumb Timecode: 00:00:08:10
```

**Comment by IAmVigneswaran** [comment]
Actually, Apple's intention of FCP chapter marker thumbnail is to provide thumbnail chapter markers in the Quicktime Player.

https://support.apple.com/en-gb/guide/final-cut-pro/verc9cacc031/mac

I feel, with our tool, we are already proving ample options to the users to set any frame for thumbnail with the placement of markers.

> Perhaps if we have an option to enable this, any thumb images we generate for chapter markers could also include a special "Thumb Timecode" label imprint noting the image's timecode, like this:
> 
> Marker Position: 00:00:04:12
> Thumb Timecode: 00:00:08:10

That could work. But the Thumb Timecode, would not have its own dedicate column in the CSV. It would be only use for burn-ins of label. Which make some sense.

**Comment by orchetect** [comment]
> _A chapter marker thumbnail is a still image that represents a particular chapter. In Final Cut Pro, you can choose a specific video frame from the [clip](https://support.apple.com/en-gb/guide/final-cut-pro/aside/ver9170a01b/10.6.2/mac/11.5.1) or [storyline](https://support.apple.com/en-gb/guide/final-cut-pro/aside/ver2bea6bc6/10.6.2/mac/11.5.1) you’re marking as the chapter marker thumbnail image. In supported playback apps or devices, the chapter marker thumbnail images represent their corresponding chapters._
>
> -> https://support.apple.com/en-gb/guide/final-cut-pro/verc9cacc031/mac

FCP users would use this thumbnail location to set the idea thumb for the marker.

Case in point: I'm thinking often if you have a scene or titles, often times they may fade in from black. The marker would probably be at the start of the fade when the video image is black. You'd set the thumbnail pin to 1-2 seconds later when the scene is fully visible. Would it not be useful to have that be our output image for chapter markers?

Another consideration is that FCP seems to set this thumb pin to be approx 10 frames later than the chapter marker **by default** when you first create the marker. So perhaps the CLI would produce unexpected images for chapter markers that are all offset and the user may not know why.

**Comment by IAmVigneswaran** [comment]
> Case in point: I'm thinking often if you have a scene or titles, often times they may fade in from black. The marker would probably be at the start of the fade when the video image is black. You'd set the thumbnail pin to 1-2 seconds later when the scene is fully visible. Would it not be useful to have that be our output image for chapter markers?

How about this behaviour? The default behaviour is the current behaviour. 

When using this option, `--use-chapter-marker-thumbnails true`, the tool will use  chapter pin's timecode to generate the thumbnail. And the tool will use to timecode from the chapter pin to print into the **Marker Position** column.

When `--use-chapter-marker-thumbnails true` is used, those thumbnail files generated will have `-pin` in the filename.

Example - `Marker Data Demo_V1_00_03_22_10-pin`

The default would be  `--use-chapter-marker-thumbnails false`.

What do you think? Does it make sense?

**Comment by orchetect** [comment]
I like that - seems intuitive enough without adding too much noise to the metadata.

**Comment by orchetect** [comment]
After revising this idea, I'm wondering if it would be better to simplify things.

Since users primarily think about markers based on the marker position, the only thing that should really change here is the thumbnail image for chapter markers. The position timecode should remain unchanged.

It's probably most important for a user to be able to reference the timecode in `Marker Position`, `ID`, etc. that they're used to seeing for the chapter marker.

Our CLI will simply enable using the poster offset for the image.

**Comment by IAmVigneswaran** [comment]
So, basically, "what you see is what you get" approach?

If the users sets a "Chapter Pin", the position of the "Chapter Pin" would be used to extract the image?  There is no additional flag/option required?


<img width="743" alt="Chapter Pin" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/82233d47-764c-465a-97ff-26af69ba9770">


Some ideas - 

1. The `Chapter Pin` would inherit the name of the `Chapter` marker if set to `Name` or `Notes` under naming mode?

2. To prevent conflict, if the Chapter Marker's name was `Apple`, the name of the `Chapter Pin`  would be `Apple-Chapter-Pin` ?

3. If set to `Timecode`, `Chapter Pin` would have its own timecode?

**Comment by orchetect** [comment]
No, we literally just change the image. Nothing else. By passing the CLI flag, the user already is expecting chapter markers to use their thumbnail pins.

**Comment by IAmVigneswaran** [comment]
Ahh! Noted!

We have a new flag? Like `--use-chapter-pin-image`? If enable, Chapter marker would use the Pin's image?

**Comment by orchetect** [comment]
This is now implemented.

For example, with the Marker Data Demo_V2 project, with this timeline:

<img width="900" alt="timeline" src="https://github.com/TheAcharya/MarkersExtractor/assets/11605557/54e92b1f-b449-4db9-90ff-f0af461b72ae">

Default behavior (use chapter marker position, not pin):

![chapter-pin-disabled](https://github.com/TheAcharya/MarkersExtractor/assets/11605557/08a2cfc8-93cf-4e2a-9042-79a7796211b3)

Opt-in behavior when passing `--use-chapter-marker-thumbnails` CLI flag (use chapter marker pin):

![chapter-pin-enabled](https://github.com/TheAcharya/MarkersExtractor/assets/11605557/1e4196b1-a43f-46cb-ae7b-c2d716f6fb2f)

In both cases, the marker's timecode is identical on both image labels and in the manifest: 00:00:35:23.00 for ID, position, etc.

**Comment by IAmVigneswaran** [comment]
Noted!

**Comment by orchetect** [comment]
> We have a new flag? If enabled, Chapter marker would use the Pin's image?

Yes exactly, as shown above. New flag is `--use-chapter-marker-thumbnails` to enable.

**Comment by IAmVigneswaran** [comment]
Awesome!

**Comment by orchetect** [comment]
Added in new alpha build 4 for testing:

https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.6-alpha4

**Comment by IAmVigneswaran** [comment]
Will test and report back.

**Comment by IAmVigneswaran** [comment]
Just tested, seems to be working!
