### ISSUE TITLE
Profile type added to folder naming scheme

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#35]
@orchetect Right now the folder naming scheme is FCP's `Project Name` space `Current Data` space `Current Time`.

Which results in `Marker Data Demo_V1 2023-01-02 02-42-03`.

In taking into account and consideration of profile like `Notion`, `Airtable` and others in future.

Would it make sense if we also add the profiles at the end of the folder name? Users can easily identify their folder's data set.

Example:

`Marker Data Demo_V1 2023-01-02 02-42-03 [Notion]`
`Marker Data Demo_V1 2023-01-02 02-42-03 [Airtable]`

Which can result in greater flexibility for the users. In finder, users can utilise [Smart Folder](https://support.apple.com/en-sg/guide/mac-help/mchlp2804/mac) to create custom searches of their directories and easily access them.

**Comment by orchetect** [comment]
The folder name feels long enough already but we could add the profile name. I'd forgo the square brackets as it feels superfluous though.

Ostensibly, a user will only be using one format and likely isn't exporting multiple formats (multiple CLI run passes) other than perhaps during testing.

**Comment by IAmVigneswaran** [comment]
> The folder name feels long enough already but we could add the profile name. I'd forgo the square brackets as it feels superfluous though.

Sure, I leave it to your liking. But with square brackets, I could be specific in finder searches.

**Comment by orchetect** [comment]
Ultimately a user-definable tokenized string would be most useful, rather than forcing a specific format. It could default to our current format of `FCPXML-base-name date-stamp`

A set of metadata tokens could be provided and a string template could be built using them. The tokens would be substituted with their corresponding values.

For example, tokens:
- `filename`: the base FCPXML filename, excluding its file extension
- `date`: date stamp
- `profile`: profile name

So a template such as:

```
":filename: :date: [:profile:]"
```

Would produce a folder with the name:

```
Marker Data Demo_V1 2023-03-21 09-45-22 [Notion]
```

This allows extensibility, as more tokens could be added in future.

**Comment by orchetect** [comment]
Or instead of templates, just have a few pre-defined formats and allow a selection of one.

For example, a CLI flag like `--folder-name` with a few preset options:

- `--folder-name short`
  ```
  Marker Data Demo_V1
  ```

- `--folder-name medium`
  ```
  Marker Data Demo_V1 2023-03-21 09-45-22
  ```

- `--folder-name long`
  ```
  Marker Data Demo_V1 2023-03-21 09-45-22 [Notion]
  ```

**Comment by IAmVigneswaran** [comment]
> Or instead of templates, just have a few pre-defined formats and allow a selection of one.

Perfect!

**Comment by orchetect** [comment]
This is done. Will be in next alpha build.

**Comment by IAmVigneswaran** [comment]
@orchetect I was playing with the new `--folder-format` feature.

I think we need to tweak: 

- `--folder-format short` into this fashion.

  ```
  Marker Data Demo_V1 (1)
  ```

If the same same folder name exists in the directory

  ```
  Marker Data Demo_V1 (2)
  ```

That way, all created folder name are unique.

Right now it errors out with:

`Error: Failed to create output dir "/Users/XXX/Desktop/Output/Marker Data Demo_V2": Directory with path already exists: /Users/XXX/Output/Marker Data Demo_V2`

**Comment by orchetect** [comment]
This is done. Will be in 0.2.4.

![folder-uniquing](https://github.com/TheAcharya/MarkersExtractor/assets/11605557/ee4a8ff7-efeb-4d46-ac35-013fab4a4315)

**Comment by IAmVigneswaran** [comment]
Awesome!

**Comment by IAmVigneswaran** [comment]
Just tested in 0.2.4 and it works.

Will close this for now.
