### ISSUE TITLE
Clip Name is a hybrid of clip name and its file extension

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#36]
## Issue

I spotted an odd behavior in the logic.

https://github.com/TheAcharya/MarkersExtractor/blob/b14a8d02ffa6323a006589dd324c6d87278cb470/Sources/MarkersExtractor/Extractors/FCPXMLMarkerExtractor.swift#L222-L224

The Clip Name field in the CSV output is neither the clip name nor the clip filename. It's actually a custom Frankenstein of both which is odd.

Consider:
- if the clip uses a video file called "Test video.mp4", and
- in the FCP timeline the clip is renamed to "My Clip", then
- the CLI will output a Clip Name of "My Clip.mp4"

## Proposal

There are a few possible solutions:

1. We should drop the appended file extension in the Clip Name field.
   - We could then add a Clip Filename field that actually contains the full filename on disk of the video asset. Or just keep the Clip Name field.
2. We could retain the file extension but enclose it in parentheses after the clip name so the entire field doesn't look like a filename
   - ie: "My Clip (mp4)"

**Comment by IAmVigneswaran** [comment]
> The Clip Name field in the CSV output is neither the clip name nor the clip filename. It's actually a custom Frankenstein of both which is odd.
> 
> Consider:
> 
> if the clip uses a video file called "Test video.mp4", and
> in the FCP timeline the clip is renamed to "My Clip", then
> the CLI will output a Clip Name of "My Clip.mp4"

In FCP, users can rename their source clips.

> There are a few possible solutions:
> 
> We should drop the appended file extension in the Clip Name field.
> We could then add a Clip Filename field that actually contains the full filename on disk of the video asset. Or just keep the Clip Name field.
> We could retain the file extension but enclose it in parentheses after the clip name so the entire field doesn't look like a filename
> ie: "My Clip (mp4)"

I think the best approach would be to only utilise the source clip filename. Which means, it would be Test video.mp4. That way users can search and locate the exact source file in their drive if need.

**Comment by orchetect** [comment]
So you suggest the CSV "Clip Name" field would be renamed "Clip Filename" and would contain the filename of the clip's asset on disk.

Wouldn't Clip Name be a useful field though? I'm thinking clip name is whatever a user is used to seeing as the name of the clips on their timeline when working in FCP.

**Comment by IAmVigneswaran** [comment]
> So you suggest the CSV "Clip Name" field would be renamed "Clip Filename" and would contain the filename of the clip's asset on disk.

When you rename a clip in FCP, it is only metadata that is stored in FCP's Library. Hence, FCP never renames the source clips for obvious reasons.

Actually, I am somewhat trying to follow the output "style" of [Producer's Best Friend](https://intelligentassistance.com/producer-s-best-friend.html) app. Here is the [demo](https://www.youtube.com/watch?v=LQGO1t-rI1A) of the app. In the demo, you can see that "Clip Name" column means the source filename.

![PBF](https://user-images.githubusercontent.com/118706051/210310752-014d2c8e-b65d-41c1-8a9b-666f3aba8c06.jpg)

> Wouldn't Clip Name be a useful field though? I'm thinking clip name is whatever a user is used to seeing as the name of the clips on their timeline when working in FCP.

I rarely rename my clips in FCP. I might rename Compound Clips or Multi-Cam Clips. But never source clips in FCP. Even if I did, I would also rename the source as well. I usually rename my clips in finder before I import them in FCP. But I can only speak for myself. Most FCP users I know don't rename their source clips once in FCP. This is to ensure, what is their drive directory matches with FCP's browser list.

**Comment by orchetect** [comment]
> you can see that "Clip Name" column means the source filename

Except that Clip Name and Clip Filename are both actual things that we have metadata for, so they are not the same thing. It would be more clear to name the field "Clip Filename" in the CSV. Because the field contents are not the clip name, it is the filename.

> But I can only speak for myself.

That's why I am bringing this topic up because some users may rename clips either intentionally or unconsciously during editing their FCP project. At least "Clip Filename" makes it plainly obvious what it is if we only output filename.

**Comment by IAmVigneswaran** [comment]
> That's why I am bringing this topic up because some users may rename clips either intentionally or unconsciously during editing their FCP project. At least "Clip Filename" makes it plainly obvious what it is if we only output filename.

Okay we change the column name to "**Clip Filename**". 👍

**Comment by orchetect** [comment]
Done. Will be in next alpha build.

Both **Clip Name** and **Clip Filename** columns are included. This covers all bases. Generators won't have filenames of course so Clip Filename will be blank for those.
