### ISSUE TITLE
Profiles & Formats (Youtube Chapters)

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#38]
This could be added in the 0.2 or 0.2.1 release. 

There is a [paid app](https://intelligentassistance.com/creator-s-best-friend.html) that does this. Since our tool is able to read and parse out FCP's Markers, I believe it makes sense to add this which could be valuable for the broader Youtube community.

For Youtube Chapters, the output file could be a plain `.txt` file. For this format, no csv or images will be created.

Marker Position Marker Name

Example -
```
0:00 Intro
0:53 Chapter 2
1:39 Chapter 3
3:21 Chapter 4
4:37 Chapter 5
6:47 Chapter 6
7:41 Chapter 7
```

**Comment by IAmVigneswaran** [comment]
@orchetect Apart from our Notion and Airtable Profiles (which is highly database centric), I think it would be great if we can prioritise and include this Profile in the during public beta of our Marker Data app. Furthermore users could realise the potential usefulness of our app.

**Comment by orchetect** [comment]
A new YouTube profile that that only outputs a `.txt` file. No manifests (csv, json) and no thumbnails.

Is there a specific format for the text file? How does the user use this?

**Comment by IAmVigneswaran** [comment]
> A new YouTube profile that that only outputs a .txt file. No manifests (csv, json) and no thumbnails.

Yes.

> It appears to be M:SS MarkerName. In the event of > 59:59, I assume the timestamp becomes H:MM:SS?

Yes, I assume it is in `H:MM:SS`

> If consistent with the existing done file(s), it would be done.json with "txtPath" key and the path to the text file as the value.

We don't exactly need the done file for this profile. But as you mention to keep it consistent, we can still generate it with the .txt path, if the end user needs any automation.

**Comment by IAmVigneswaran** [comment]
Example of Youtube video with timestamp with longer than 1hr.

https://www.youtube.com/watch?v=bYsL3CwDUmA

**Comment by orchetect** [comment]
I now have this implemented as a new export profile.

For sake of clarity: We are outputting elapsed real time (wall clock time). YouTube videos start at 0:00, so we treat times as offsets from the project start (and not absolute times).

For example:

Using a project start timecode of 00:59:50:00 @ 25fps:

| Marker | Marker Position |
| --- | --- |
| Marker 1 | 01:00:01:00 |
| Marker 2 | 01:00:34:17 |
| Marker 3 | 01:00:54:00 |

Would output as this for YouTube Chapters:

```
0:11 Marker 1
0:44 Marker 2
1:04 Marker 3
```

**Comment by IAmVigneswaran** [comment]
Awesome! Thanks for adding this new profile.

**Comment by IAmVigneswaran** [comment]
Will close this for now. Will re-open back, if users reports any issues.
