### ISSUE TITLE
Add clip metadata manifest fields

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#39]
@samplue Sam Pluemacher suggest - 

> The CSV includes the clip name, but I would love to see the "Reel" information as well. For me the Reel information is even more important than the clip name.

@orchetect Can we add "Reel" "Scene" & "Take" columns as well? This enhancement links and circles back to #36 & #7

We would now have `Clip Name`, `Clip Source Filename`, `Reel`, `Scene` & `Take` columns.

Clip Name = It would be name of Multicam, Synchronize clips or Compound within FCP.

I believe it can get rather complex when we have Multicam, Synchronize clips or Compound. If a marker is placed on a Multicam clip, we can print the name of the Multicam clip for the `Clip Name` column and extract the metadata of that Multicam clip for `Reel`, `Scene` & `Take` information associate with these type of special clips.

Maybe there is some logic where if clips are Multicam, Synchronize clips or Compound types, `Clip Source Filename` columns would be empty or print it as `Skipped` or `Not Parsed`? With Multicam, Synchronize clips or Compound types, there can be umpteen number of source clips nested deep in these types. It may not make sense to print Source Filenames for Multicam, Synchronize clips or Compound types.

**Comment by samplue** [comment]
An option to include `Start Source Timecode` and `End Source Timecode` as well as `Media Duration` for the clips would be a nice & welcome addition.

**Comment by orchetect** [comment]
`Clip In` and `Clip Out` Timecode as well as `Media Duration` should be easy to do.

However I ran into a funny issue when investigating the clip and camera metadata.

Final Cut Pro only seems to export this data for clips that use actual video assets. It doesn't export it for things like Titles or Clouds generator (even though it allows you to enter text for its Reel, Scene, Take, Camera Angle, and Camera Name).

I suppose that doesn't matter that much since users probably only care about this metadata for actual video clips any how.

**Comment by IAmVigneswaran** [comment]
> I suppose that doesn't matter that much since users probably only care about this metadata for actual video clips any how.

Yes. It should not matter for those Titles. Motion Templates and Generators. Those fields can be empty in our csv file for these assets/Clip Type.

**Comment by orchetect** [comment]
I just realized that for the same reason [why we should remove `Clip Filename`](https://github.com/TheAcharya/MarkersExtractor/issues/62#issuecomment-1823737088) from the output manifest, `Media Duration` is not a viable field. Sync clips, compound clips, and multicam clips can contain more than one clip of different lengths and reference more than one media file. In those cases it would be ambiguous what data should populate the field and may end up being half-useful at best and confusing at worst.

**Comment by IAmVigneswaran** [comment]
Noted!

**Comment by IAmVigneswaran** [comment]
Hopefully in subsequent build, we can add, `Reel`, `Scene`, `Take`, `Clip In` and `Clip Out` fields.

<img width="1392" alt="update-output-manifest" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/7c76c68b-4550-47a3-9bc4-70a72f530055">

**Comment by orchetect** [comment]
Just to be clear, for our purposes, `Clip In` and `Clip Out` timecodes will be absolute timecodes (based on main project timeline) and not the local media's timeline.

**Comment by IAmVigneswaran** [comment]
> Just to be clear, for our purposes, `Clip In` and `Clip Out` timecodes will be absolute timecodes (based on main project timeline) and not the local media's timeline.

I believe that is what the users might be expecting. `Clip In` and `Clip Out` values based on the range used from the main project timeline.

**Comment by orchetect** [comment]
Yes, but I only mention it because within Final Cut Pro's inspector, clip start and end timecodes are shown in relation to the media's own timeline, as it can have its own arbitrary start timecode. It of course makes more sense for us to use the main (absolute) timeline context.

**Comment by IAmVigneswaran** [comment]
To bring awareness to the user, I can add a small column info (i) to both `Clip In` and `Clip Out`.

<img width="337" alt="Notion - Clip In" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/55196d21-0099-4bab-9ad8-28cffa0adc09">

**Comment by orchetect** [comment]
Probably not necessary, since absolute timecode is intuitively obvious in our case. But you could add something to the wiki docs for MarkersExtractor and Marker Data that clarifies this if you want.

**Comment by IAmVigneswaran** [comment]
Thank you! 🙏

**Comment by orchetect** [comment]
Side note: when new fields are implemented, they automatically become available as thumbnail image `--label` burn-in options.

**Comment by orchetect** [comment]
Ok implemented and seems to be working as expected in my limited testing.

FCP project:
<img width="1456" alt="timeline" src="https://github.com/TheAcharya/MarkersExtractor/assets/11605557/d75487d3-4848-4cc9-9cd6-e5bd64323661">

<img width="443" alt="inspector" src="https://github.com/TheAcharya/MarkersExtractor/assets/11605557/a6a91e56-f55e-4d52-ad29-06dce8caffec">

Manifest output:

<img width="1071" alt="manifest" src="https://github.com/TheAcharya/MarkersExtractor/assets/11605557/1ad5ac6f-d586-41eb-9a44-901543849d0b">

**Comment by orchetect** [comment]
@IAmVigneswaran new alpha build for testing:

https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.6-alpha3

**Comment by IAmVigneswaran** [comment]
Thanks for the test build! 

Just tested using Sam's sample project; seems to extract all the desired metadata.

@samplue do test it out at your end with any of your more complex projects. Thanks.

**Comment by samplue** [comment]
Thanks a lot, it's working on one of the more complex timelines! What I've noticed though, is that it will not extract the Reel information for Multicam clips. That would be important for me. It should read the active MC angle data and not the MC container information. Here's the .csv and fcpxml for further inspection.

[BRS_LOCKED6_20210521 - 01 Opening Scene.csv](https://github.com/TheAcharya/MarkersExtractor/files/15185550/BRS_LOCKED6_20210521.-.01.Opening.Scene.csv)
[BRS_LOCKED6_20210521 - 01 Opening Scene_00000000.fcpxmld.zip](https://github.com/TheAcharya/MarkersExtractor/files/15185551/BRS_LOCKED6_20210521.-.01.Opening.Scene_00000000.fcpxmld.zip)

**Comment by IAmVigneswaran** [comment]
@orchetect Would it be possible or does it makes sense to have `--use-active-multicam-metadata`?

When enabled, it would use the metadata from Multicam's active angle.

**Comment by orchetect** [comment]
It makes more sense just to use angle metadata as default behavior.

There may be other clip types that need tweaks, I only tested basic clips. Especially check ref-clips, sync-clips and audition clips as well.

**Comment by orchetect** [comment]
I believe the best approach is to first grab the container's metadata, then grab the angle's metadata and overlay it on the container's, replacing the container's keys with the angle's metadata if there are any duplicate keys.

In the XML, the angle tends to contain the `reel`, `scene`, and `shot` (take). The container tends to contain the camera information like camera name, camera ISO, etc.

**Comment by IAmVigneswaran** [comment]
We don't need the camera information like `cameraName`, `cameraISO`. Those seems a little excessive and not entirely pertains to editorial.

**Comment by orchetect** [comment]
I'm not adding them, this is for my own reference.

**Comment by orchetect** [comment]
Ok multicam metadata is now fixed. Will be in next build.

Still need to test other complex clip types which I think will also require special handling.

**Comment by orchetect** [comment]
> Generally speaking: it should always use the source media clip timecode and not the container timecodes. Or at least make this optional.

@samplue do you mind clarifying this?

**Comment by orchetect** [comment]
New alpha for testing:

https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.6-alpha5

**Comment by samplue** [comment]
> > Generally speaking: it should always use the source media clip timecode and not the container timecodes. Or at least make this optional.
> 
> @samplue do you mind clarifying this?

Please ignore that comment, I was mixing this up with something else.

Regarding alpha5, happy to confirm this will now correctly pull the Reel, Scene, etc metadata for Multicam clips on my complex test timeline.

**Comment by IAmVigneswaran** [comment]
I think we can safely release 0.3.6.
