### ISSUE TITLE
Ability to ignore disabled clips

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#4]
The tool should have a the function to ignore disabled clips.

This option could be used: `--exclude-disabled`

**Comment by orchetect** [comment]
This is fairly easy to implement and could be in 0.2.6 probably.

**Comment by orchetect** [comment]
Question:

Would it make sense for exclusion to be default behavior, but provide an opt-in flag like `--include-disabled` to extract them?

**Comment by IAmVigneswaran** [comment]
Makes sense. Let's go for it.

**Comment by IAmVigneswaran** [comment]
> > [disabled clip] exclusion to be default behavior, but provide an opt-in flag like `--include-disabled` to extract them
> 
> Implemented in DAWFileKit. Will add CLI flags to MarkersExtractor shortly.

Awesome! Does it make sense to make it automatic? If a clip is disabled, any Markers on the clip will be ignored.

**Comment by orchetect** [comment]
Yes, omitted by default as I said. Have to opt-in to including disabled clips.

This is done. Will be in 0.3.4.

**Comment by IAmVigneswaran** [comment]
Just tested seems to be working! Will close this for now. Thank you.
