### ISSUE TITLE
Bypass media option

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#40]
@orchetect Can we have a `--bypass-media` option? This is mainly intended for testing purpose.

When used, the tool would ignore the media file and still proceed to generate the .csv and icon files (if applicable).

**Comment by orchetect** [comment]
`--no-media` might make more sense

**Comment by orchetect** [comment]
Should we remove the Image Filename field from the CSV in that case?

**Comment by IAmVigneswaran** [comment]
> Should we remove the Image Filename field from the CSV in that case?

I think we should since no images are generated.

**Comment by orchetect** [comment]
This is now added. Will be in next alpha.

**Comment by orchetect** [comment]
Just realized the CSV still has the Image Filename column - I'll remove that in the next build. Otherwise, this feature is working in my testing.
