### ISSUE TITLE
Can't able to generate and write log file if file is not present

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#42]
### Bug Description, Steps to Reproduce, Crash Logs, Screenshots, etc.

@orchetect The CLI and library are unable to generate or write a log file if the file (example: log.txt) is not present

`Error: Cannot write log file at "/Users/xxx/Desktop/0.2.0/log.txt"`

The tool should be able to auto generate a log file even if the specified file does not exist in the given path.

CC: @theogscott

**Comment by orchetect** [comment]
Ah thanks for the heads-up. This is an easy fix.
