### ISSUE TITLE
CFURLCopyResourcePropertyForKey failed because it was passed a URL which has no scheme

### ISSUE THREAD

**Issue by theogscott** [TheAcharya/MarkersExtractor#43]
### Bug Description, Steps to Reproduce, Crash Logs, Screenshots, etc.

I am using MarkersExtractor and a Swift Package Library in a GUI (SwiftUI) app.

The extractor reads the input file (FCPXML), and can create the output folder, so there are no issues with Read and Write permissions, but the problem occurs when the extractor makes the icons file, and then the above error occurs. 

The error occurs at line 212 of ExportProfile Export.swift

See attached  Screenshot where the error is "caught" for the caller.

![CleanShot 2023-04-23 at 09 59 44](https://user-images.githubusercontent.com/6077716/233851717-e41b8511-0f64-4c81-8c96-14fb0f8452dc.png)

**Comment by orchetect** [comment]
Are you able to attach a copy of the FCPXML file?

**Comment by orchetect** [comment]
Can you show me the full CLI command line invocation including all the command line arguments?

This is likely a formatting issue with the path passed into the CLI.

**Comment by theogscott** [comment]
Here is the full code snippet for calling to cli entry point from where I handle the drag and drop of the file in the GUI

                .onDrop(of: [(kUTTypeFileURL as String)], isTargeted: nil, perform: { providers, _ in
                    for provider in providers {
                        // Check if the provider can load a file URL
                        if provider.canLoadObject(ofClass: URL.self) {
                            // Load the file URL from the provider
                            let _ = provider.loadObject(ofClass: URL.self) { url, error in
                                if let fileURL = url {
                                    // Handle the file URL
                                    print("Dropped file URL: \(fileURL.absoluteString)")
                                    DispatchQueue.main.async {
                                        do {
                                            let outputDirString = UserDefaults.standard.string(forKey: "exportFolderPath") ?? FileManager.default.temporaryDirectory.absoluteString
                                            let outputDirUrl = URL(string: outputDirString) ?? FileManager.default.temporaryDirectory
                                            let fcpxmlFilePathName = fileURL.absoluteString
                                            let fcpxmlFile: FCPXMLFile = .init(File(fileURL))
                                            var settings = try MarkersExtractor.Settings(
                                                fcpxml: fcpxmlFile,
                                                outputDir: outputDirUrl)
                                            print("output is going to \(settings.outputDir.absoluteString)")
                                            try MarkersExtractor.extract(settings)
                                            print("Ok")
                                        } catch {
                                            DispatchQueue.main.async {
                                                errorViewModel.errorMessage  = error.localizedDescription
                                                print("Error: \(error.localizedDescription)")
                                            }
                                            
                                        }
                                    }
                                } else if let error = error {
                                    // Handle the error
                                    print("Error loading file URL: \(error.localizedDescription)")
                                }
                            }
                        }
                    }

**Comment by theogscott** [comment]
And here is the log for the above:
Dropped file URL: file:///Users/tgs/Movies/markerData/Scripts/Render/Marker%20Data%20Demo_V1.fcpxmld/
output is going to /Users/tgs/Movies/markerData/Scripts/Output
2023-04-26T05:25:55+0100 info MarkersExtractor : [MarkersExtractor] Using Notion (csv2notion) export profile.
2023-04-26T05:25:55+0100 info MarkersExtractor : [MarkersExtractor] Extracting markers from "/Users/tgs/Movies/markerData/Scripts/Render/Marker Data Demo_V1.fcpxmld".
2023-04-26T05:25:55+0100 notice FCPXMLMarkerExtractor : [MarkersExtractor] Marker "Marker on Title" at 00:03:45:03 is out of bounds of its parent clip Basic Title 2 - Basic Title (00:03:32:08 - 00:03:44:17) and will be omitted.
2023-04-26T05:25:55+0100 info MarkersExtractor : [MarkersExtractor] Found project media file "/Users/tgs/Movies/markerData/Scripts/Render/Marker Data Demo_V1.mov".
2023-04-26T05:25:55+0100 info MarkersExtractor : [MarkersExtractor] Generating metadata file(s) with PNG thumbnail images into "/Users/tgs/Movies/markerData/Scripts/Output/Marker Data Demo_V1 2023-04-26 05-25-55".
2023-04-26T05:25:55+0100 info markersExport : [MarkersExtractor] Exporting marker icons.
Error: Failed to export: Failed to write marker icons.

**Comment by theogscott** [comment]
Here is the FCPXML files:

[Marker Data Demo_V1.fcpxmld.zip](https://github.com/TheAcharya/MarkersExtractor/files/11329424/Marker.Data.Demo_V1.fcpxmld.zip)

**Comment by orchetect** [comment]
The API has updated slightly. Use the file URL directly and avoid `absoluteString` where possible.

Pull the latest **main** branch, and replace your `do { }` block with the following:

```swift
do {
    let outputDirURL: URL = {
        guard let outputDirString = UserDefaults.standard.string(forKey: "exportFolderPath") else {
            return FileManager.default.temporaryDirectory
        }
        return URL(string: outputDirString) ?? FileManager.default.temporaryDirectory
    }()
    let settings = try MarkersExtractor.Settings(
        fcpxml: .init(fileURL),
        outputDir: outputDirURL
    )
    print("output is going to \(settings.outputDir)")
    try MarkersExtractor(settings).extract()
} catch {
```
