### ISSUE TITLE
Profiles & Formats (Airtable (JSON))

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#44]
@orchetect I wondering if we can add an additional profile for Airtable that is in JSON format.

If @theogscott going to use [AirtableKit](https://github.com/academypoa/AirtableKit), it would be great if the CLI and Library is able to provide a native way to generate the output data in JSON format.

From the example of [AirtableKit](https://github.com/academypoa/AirtableKit), the library will aspects data in this format :

``` swift
let fields: [[String: Any]] = [
  [
    "name" : "Record 1",
    "isCool" : true
    "age" : 25,
    "updatedTime" : Date()
  ],
  [
    "name" : "Record 2",
    "isCool" : true
    "age" : 22,
    "updatedTime" : Date()
  ]
]

let records = fields.map { Record(fields: $0) }

let publisher = airtable.create(tableName: tableName, records: records)

```

I wonder if it would allow easier facilitation of uploading the data directly to Airtable via Marker Data App. Hence, @theogscott could pass the .json file programmatically.

The current Airtable profile could be rename to Airtable (CSV). We could still keep the this profile for users who want to upload the data manually.

**Comment by IAmVigneswaran** [comment]
Yes, the key column names would be identical to our Airtable CSV.

**Comment by orchetect** [comment]
Why not just output both a csv file and a json file? No arguments or options required. The done file can contain both file paths.

**Comment by orchetect** [comment]
This is implemented. Will be in next alpha build.

**Comment by IAmVigneswaran** [comment]
> Why not just always output both a csv file and a json file? No additional arguments or options required and it's no extra overhead really.
> 
> The **done** file can contain both file paths.

Yes, that could work too! Thank you.

**Comment by IAmVigneswaran** [comment]
Even though [Airlift](https://github.com/TheAcharya/Airlift) supports both `.csv` or `.json`, I think we can remove creation of  `.json` file for Airtable profile. It becomes a little redundant in our use-case.

This is to standardise output format filetype.

**Comment by orchetect** [comment]
There isn't any harm in generating both files and it takes zero time and very little disk space. If it's ever needed in future then you already have it.

**Comment by IAmVigneswaran** [comment]
> There isn't any harm in generating both files and it takes zero time and very little disk space. If it's ever needed in future then you already have it.

True, there is no harm.

We just the code in but we just off the generation part for now?

**Comment by orchetect** [comment]
Sure, if you want.

**Comment by IAmVigneswaran** [comment]
Thank you!
