### ISSUE TITLE
Change version numbering

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#45]
@orchetect In the next build of CLI / Library can we change the version numbering?

Theo, mentions and request that it will helpful if we make the cli version numeric, then the GUI will automatic pull the latest version of the CLI library. Having character  such as -alpha- makes it impossible for package manager like (Swift PM), to update.

![CleanShot 2023-04-28 at 07 40 08](https://user-images.githubusercontent.com/118706051/235077905-9a943c76-b579-454e-a794-1e505fb7f1e8.jpeg)

![CleanShot 2023-04-28 at 07 40 58](https://user-images.githubusercontent.com/118706051/235077927-792bb031-1a8d-4846-954f-d49f3d97452b.jpeg)

We drop the alpha and date suffix, and use `0.2.1`, `0.2.2`, `0.2.3` and such.

Thank you.

CC: @theogscott

**Comment by orchetect** [comment]
We can drop alpha and just move to SemVer.

**Comment by orchetect** [comment]
0.2.0 released.
