### ISSUE TITLE
More granular error throwing

### ISSUE THREAD

**Issue by theogscott** [TheAcharya/MarkersExtractor#46]
### Bug Description, Steps to Reproduce, Crash Logs, Screenshots, etc.

If for some reason when we execute `MarkersExtractor(settings).extract()` it can happen that the user don't have sufficient permissions, we want to report that to user.

An example of such error produced: "Error: Failed to export: Error finding media for "Marker Data Demo_V1": The file “Render” couldn’t be opened because you don’t have permission to view it."

Sample code: 

```swift
DispatchQueue.global(qos: .background).async {
    do {
        let outputDirURL: URL = UserDefaults.standard.exportFolder
        let settings = try MarkersExtractor.Settings(
            fcpxml: .init(fileURL),
            outputDir: outputDirURL,
            exportFormat: settingsStore.selectedExportFormat.markersExtractor,
            imageFormat: settingsStore.selectedImageMode.markersExtractor,
            excludeRoleType: settingsStore.selectedExcludeRoles.markersExtractor
        )
        print("output is going to \(settings.outputDir)")
        try MarkersExtractor(settings).extract()
        self.completedOutputFolder = outputDirURL
        showingOutputInfinder = true
        print("Ok")
    } catch {
        DispatchQueue.main.async {
            errorViewModel.errorMessage  = error.localizedDescription
            print("Error: \(error.localizedDescription)")
        }
        
    }
}
```

Neither the catch or the line `self.completedOutputFolder = outputDirURL` is reached.

Sample if console log:
```
Dropped file URL: file:///Volumes/Lacie_Install_macOS_Catalina/Users/tgs/tmp/MarkersExtractor/dropbox/Scripts/Render/Marker%20Data%20Demo_V1.fcpxmld/
output is going to file:///Users/tgs/Movies/Marker%20Data/
2023-04-28T16:20:35+0100 info MarkersExtractor : [MarkersExtractor] Starting
2023-04-28T16:20:35+0100 info MarkersExtractor : [MarkersExtractor] Using Airtable export profile.
2023-04-28T16:20:35+0100 info MarkersExtractor : [MarkersExtractor] Extracting markers from "/Volumes/Lacie_Install_macOS_Catalina/Users/tgs/tmp/MarkersExtractor/dropbox/Scripts/Render/Marker Data Demo_V1.fcpxmld".
2023-04-28T16:20:35+0100 notice MarkersExtractor : [MarkersExtractor] Marker "Marker on Title" at 00:03:45:03 is out of bounds of its parent clip Basic Title 2 - Basic Title (00:03:32:08 - 00:03:44:17) and will be omitted.
2023-04-28T16:20:35+0100 info MarkersExtractor : [MarkersExtractor] Project start timecode: 00:00:00:00 @ 25 fps.
2023-04-28T16:20:35+0100 info MarkersExtractor : [MarkersExtractor] Generating metadata file(s) with GIF thumbnail images into "/Users/tgs/Movies/Marker Data/Marker Data Demo_V1 2023-04-28 04-20-35".
Error: Failed to export: Error finding media for "Marker Data Demo_V1": The file “Render” couldn’t be opened because you don’t have permission to view it.
```

**Comment by theogscott** [comment]
Ideally we if the error can be thrown, so it can be reported in the catch via an Alert.

**Comment by orchetect** [comment]
That specific error is of type `MarkersExtractorError.runtimeError` containing the verbose error message.

To clarify, you want an additional `MarkersExtractorError` error case specifically for file/disk permission errors?

**Comment by orchetect** [comment]
I spent a bit of time and went through the whole library adding specialized error cases, replacing `.runtimeError` and `.validationError`.

All errors thrown by `MarkersExtractor().extract()` will be of type `MarkersExtractorError.runtimeError` and you can switch case on it to get specific error cases. There are two or three hierarchical levels.

https://github.com/TheAcharya/MarkersExtractor/blob/ef726c7c7ced4e51be6e64127e671ed2fffcf1a6/Sources/MarkersExtractor/MarkersExtractorError.swift#L10-L15

https://github.com/TheAcharya/MarkersExtractor/blob/ef726c7c7ced4e51be6e64127e671ed2fffcf1a6/Sources/MarkersExtractor/MarkersExtractorError.swift#L30-L41

https://github.com/TheAcharya/MarkersExtractor/blob/ef726c7c7ced4e51be6e64127e671ed2fffcf1a6/Sources/MarkersExtractor/MarkersExtractorError.swift#L83-L91

**Comment by IAmVigneswaran** [comment]
@milanvarady Not sure if you can utilise errors thrown from MarkersExtractorError and send it to the Marker Data Dialogue box when processing the FCPXML and the video file.

**Comment by orchetect** [comment]
The errors thrown can still produce human-readable descriptions as before, by getting the `localizedDescription` of the error -- if you don't require switching error cases in order to handle specific error conditions.
