### ISSUE TITLE
Async Branch

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#50]
@orchetect The previous dev created [Async](https://github.com/TheAcharya/MarkersExtractor/tree/async) to add and support asynchronous functions. I am not entirely sure of it function and purpose. Feel free to delete the branch, if it is not needed. Thank you.

**Comment by orchetect** [comment]
I saw that, but I've already worked through substantial refactors and have started implementing concurrency.

**Comment by orchetect** [comment]
This is actually redundant. Async is concurrency and I opened an issue for that already.
