### ISSUE TITLE
Ability to exclude specific roles by name

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#57]
@orchetect Right now we have `--exclude-exclusive-roles` #5. 

I wondering if we can also have `--exclude-role`? 

<img width="315" alt="user-defined-roles" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/46102cf7-c959-4bbf-8271-57a3baf1dab2">

With `--exclude-role`, users have to provide the EXACT name (case-sensitive) of the roles.  It would work for both custom **Video** and **Audio** Roles.

`--exclude-role FIXING,VFX`

Users can add more roles by using a `,`.

**Comment by orchetect** [comment]
I thought we decided that the user would deselect roles before exporting the FCPXML?

We would need to know whether each excluded role is a video role or audio role if we implemented this. It would probably be `--exclude-video-role X` and `--exclude-audio-role X`.

**Comment by orchetect** [comment]
I'm guessing if we add this, we will also need an isolated method in the library to parse and return a list of roles in the FCPXML so the GUI app can display them for selection by the user.

**Comment by IAmVigneswaran** [comment]
> I thought we decided that the user would deselect roles before exporting the FCPXML?
> 
> We would need to know whether each excluded role is a video role or audio role if we implemented this. It would probably be `--exclude-video-role X` and `--exclude-audio-role X`.

Yes, users can obviously deselect roles before exporting. But in hindsight for integrating FCP's Share Destination to the GUI APP, users don't have to export the video multiple times? That would be the key advantage of having this?

Especially 1 hour + complex timelines. They may have 10+ different roles in their FCP libraries. They may not want to disable/deselect the their roles for number of reasons. 

> I'm guessing if we add this, we will also need an isolated method in the library to parse and return a list of roles in the FCPXML so the GUI app can display them for selection by the user.

My idea is, user would key in manually the roles they want to exclude. Not the best elegant approach. But I believe it would work.

We can have a field for **Exclude Video Role** and a field for **Exclude Audio Role**.  They can key in `FIXING,VFX` as such. Any roles to exclude. It would be case-sensitive.

This would/could be ideal for users breaking down large timeline reel by reel, episode by episode or scene by scene. During initial setup of the their timeline. users would always have their go to custom roles "template".

Since we have the configuration panel, those setting would be saved and can be deleted at anytime.

**Comment by orchetect** [comment]
> user would key in manually the roles they want to exclude. Not the best elegant approach.

The library would be using an array of strings to do filtering. The GUI selection would be a bonus feature if there's time, or if it's easy enough to implement.

**Comment by IAmVigneswaran** [comment]
> > user would key in manually the roles they want to exclude. Not the best elegant approach.
> 
> The library would be using an array of strings to do filtering. The GUI selection would be a bonus feature if there's time, or if it's easy enough to implement.

Yes. It would be a cool feature! Drag & Drop the library, on to a drop zone within the preference. All the roles would have captured and stored for the particular configuration. 

Maybe after our initial public release? Manually keying in the GUI for time-being.

**Comment by orchetect** [comment]
This should be fairly trivial to implement now after the parser refactors.

FYI it's also now pretty easy to generate a list of roles used in a FCPXML file - audio, video, and caption roles. So if Marker Data wants to give the user a selection list after loading the FCPXML it would be possible.

**Comment by IAmVigneswaran** [comment]
Maybe we have a switch / command to generate a list (.txt or .json) file.

We can have a tab in General Settings, call roles. **Roles**. We move all Roles related setting into that Tab.

User, can drag and drop their timeline into a roles selection zone. Marker Data would cache and capture that generate list.

User can make the selection from there.

@milanvarady

Something we can add  this feature in post 1.0 public release of Marker Data. Maybe in 1.1 or 1.2.

**Comment by orchetect** [comment]
I could make the API really simple and let you know how to get the list of roles using the library. You wouldn't need a text file to get the list, if that's what you mean. If you want to open an Issue on Marker Data's repo to discuss later, that's probably best.

**Comment by IAmVigneswaran** [comment]
> I could make the API really simple and let you know how to get the list of roles using the library. You wouldn't need a text file to get the list, if that's what you mean. If you want to open an Issue on Marker Data's repo to discuss later, that's probably best.

Will do that shortly!

**Comment by orchetect** [comment]
> It would work for both custom Video and Audio Roles.

Essentially this would work for any role (audio, video, caption) and no matter whether it's a default role or user-defined. Just supply the role name and it will be filtered.

This is somewhat related to #8 where we want to pick the caption role to use. (Except that would be a filter to retain only the specified caption role, not to omit it.)

I'm wondering if we can unify this concept a bit.

Maybe it's a little more effort on the user's part, but what if we went with the filter-out approach for everything?

- All video, audio, and caption roles are enabled by default.
- If a user wants only one caption role, they would have to **filter out all other caption roles**.

This would unify the concept and reduce the number of CLI flags we have to deal with.

**Comment by orchetect** [comment]
It's easier to understand if you think of captions as being 'converted' to markers. Then all other filters apply to markers and captions uniformly. Captions have a slightly different role name format but it would work the same way. And those details can be ironed out.

> If users want to exclude them, they can simply uncheck them in the GUI?

Yes, since our filtering ability would be exclusion based. If every role remains checked, then no filtering options need to be used. Only when roles are unchecked.

The only reason we need three CLI flags:
```
--exclude-audio-role "RoleName"
--exclude-video-role "RoleName"
--exclude-caption-role "RoleName"
```
is that users may in unusual circumstances have the same role name for a video role and an audio role, and we would like to distinguish between them.

**Comment by orchetect** [comment]
Actually we don't need three, only one.

I just did a test in FCP and it will not let you have a duplicate role name between audio an video roles.

![unique-role](https://github.com/TheAcharya/MarkersExtractor/assets/11605557/8854d0c0-5546-4bf3-a89d-b1e9961d2286)

**Comment by IAmVigneswaran** [comment]
Even-though, I suggested for this feature 😅, upon further pondering, I think we should we totally abandon this manual `exclude role` route.

To keep things simple. users could just do it right within Final Cut Pro?

In Final Cut Pro - 

**For Caption**
In FCP, only 1 caption role can be active at any given time. If user want to use any of their caption role as markers, they can active that role and send the timeline.

**For Audio and Video**
If users don't want to  to extract markers from a particular role or sub-role in their timeline, they simply deactivate the that particular role, MarkersExtractor would exclude all markers from that deactivated role.

MarkersExtractor would do it automatically base on active or inactive state of the roles in the FCPXML.

Any thoughts?

**Comment by orchetect** [comment]
That's not going to work for a ton of reasons actually.

It's not possible to tell from the FCPXML what caption role is enabled. FCP does not output that information.

Also there may be a use case for importing more than one Caption role so I would be hesitant to restrict that artificially.

And I also found that disabling roles in FCP has no effect on the FCPXML that is exported. There is no way to know what roles are enabled or disabled because FCP does not output that information.

**Comment by orchetect** [comment]
This is done. Will be in 0.3.0.

**Comment by IAmVigneswaran** [comment]
Thank you!

**Comment by IAmVigneswaran** [comment]
> It's not possible to tell from the FCPXML what caption role is enabled. FCP does not output that information.

https://github.com/CommandPost/FCPCafe/issues/303

FYI, I have send a request to Apple via [Apple Feedback Assistant](https://developer.apple.com/bug-reporting/). Maybe you can  submit this feature request as well? That way, Apple can move this request up in their list of to-do?
