### ISSUE TITLE
Adding Dry Run Option

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#58]
@orchetect I believe right now our tool/library would throw an error during the extraction operation if it detects any.

Is there a possibility where the tool might throw an error half-way during the extraction process? Which can result with in-complete image set?

In anticipation of large complex timelines, I am wondering if adding a `--dry-run` would make sense?

When enable, MarkersExtractor would perform the scan of the FCPXML base on provided switches/options without starting the image extraction. It is somewhat similar to `--no-media` #40. 

But the difference its, it won't create the `done.json` file at its first run. Upon successful passing of Dry Run, MarkersExtractor would perform than start the actual extraction operation.

Any thoughts?

**Comment by orchetect** [comment]
Valid idea, but would require an extensive refactor.

**Comment by IAmVigneswaran** [comment]
I believe we can defer or close this feature.
