### ISSUE TITLE
Ability to support Auditions in FCP

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#6]
FCPXML contains all the information pertaining clips within each Audition. But only 1 will be active at any given time.

https://support.apple.com/en-sg/guide/final-cut-pro/verbbd3587d/mac

In the next or subsequent build, the tool should only parse out the markers on the active Auditions. Any markers of inactive clip within the Auditions will be ignored automatically.

![FCP-Auditions](https://user-images.githubusercontent.com/118706051/207221535-53f0005a-8b6a-4df9-80d4-a2bfbdc078d1.gif)

**Comment by orchetect** [comment]
This is now the default behavior after the parser refactors. You can test it out in the next release.

**Comment by IAmVigneswaran** [comment]
Audition now works in 0.2.4. 

MarkersExtractor only reads the markers on the "Active" Audition clip. Which is the correct behaviour.
