### ISSUE TITLE
Add `Clip Type` export manifest column

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#62]
In the recent DAWFileKit refactors, it's now easy to filter clip types.

It would be fairly easy to add the ability to:
- extract extracted markers only from certain clip types, or
- extract all markers except for markers on certain clip types

This would be similar to the ability to filter by roles, but it would be more broad. Would this be useful?

To be clear, the following are the clip types that could be specified. Some may be a little vague or unfamiliar to average users, so an explanation could be accompanied with them.

https://github.com/orchetect/DAWFileKit/blob/1461eec9441c2eed644a0d6622188975fa5632e5/Sources/DAWFileKit/FinalCutPro/FCPXML/Story/Clips/Meta/FCPXML%20ClipType.swift#L13-L45

**Comment by IAmVigneswaran** [comment]
> This would be similar to the ability to filter by roles, but it would be more broad. Would this be useful?

It would be definitely be useful. We can have one of two approach?

**For Example 1 - The switch method**

```
--include-clip-type <all, audio, audition, gap, clip, liveDrawing, multicam, compound, synchronized, title> (default: all)
```

I think Example 1 creates more complexity and confusion to the user? And they will never use it.

**Example 2 - The database method**

We create a new column call `Clip Type` after `Clip Filename` in our `.csv` and `.json` file. 

Our Tool will print the value of the the `clip type` base on the maker or caption that it attached on?

I think the database method provides maximum flexibility. The user can create custom filters and criteria in their Notion or Airtable Databases. They can filter out any clip type to their desire.

Any thoughts?

<hr>

> https://github.com/orchetect/DAWFileKit/blob/1461eec9441c2eed644a0d6622188975fa5632e5/Sources/DAWFileKit/FinalCutPro/FCPXML/Story/Clips/Meta/FCPXML%20ClipType.swift#L13-L45

Does DAWFileKit  supports `Generator` Clip type?

There is also one more hidden clip type `Layered Graphic` which is basically `.psd` photoshop file.

<img width="599" alt="FCP-Clip-Types" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/ca511894-71a6-4774-b580-f4bfecd91bff">

**Comment by orchetect** [comment]
Generators are actually `video` clips internally.

This is the Clouds generator:

```xml
video ref="r2" offset="3600s" name="Clouds" start="3600s" duration="240300/2400s"/>
```

It links to an effect file:

```xml
<effect id="r2" name="Clouds" uid=".../Generators.localized/Backgrounds.localized/Clouds.localized/Clouds.motn"/>
```

So there's no actual generator clip type, and no real way to distinguish them.

**Comment by orchetect** [comment]
> We create a new column call `Clip Type` after `Clip Filename`

Actually this is a great idea and easy to implement also. For now we'll just add a new Clip Type column.

(As an aside, I'm going to remove the Clip Filename column. There's a few reasons, but Clip Name is always superior in every case.)

**Comment by IAmVigneswaran** [comment]
> Generators are actually video clips internally.

Noted! We can just call them as `Video` under `Clip Type` column .

> (As an aside, I'm going to remove the Clip Filename column. There's a few reasons, but Clip Name is always superior in every case.)

Change it to `Clip Source Filename` ?

**Comment by IAmVigneswaran** [comment]
What are all the possible values would `Clip Type` would print? 

How are we typographically outputting them?

I can update my database template.

**Comment by orchetect** [comment]
`Clip Type` has been added to the manifest output. Will be in 0.2.5.

`Clip Filename` actually presents a number of issues and I would like to remove it. It's simple for basic asset clips that only have one video file.

However for compound clips, sync clips, and multicam clips can contain clips using more than one video file. In that case it would not be clear what file to include for this field.

**Comment by orchetect** [comment]
> What are all the possible values would `Clip Type` would print?

Currently these, which are the literal internal clip types FCP uses in the XML:

```
Asset
Audio
Audition
Clip
Gap
Live Drawing
Multicam
Compound
Sync
Title
Video
```

It would take a little work but we could interpret some of these types to be more useful to the user, if needed.

One thought is that the Audition type could change to the actual clip type contained within the audition, like this:

```
Compound (Audition)
```

Or just make it seemless as the user probably doesn't care that it's an audition, they just care what clip type is contained within:

```
Compound
```

**Comment by IAmVigneswaran** [comment]
> One thought is that the Audition type could change to the actual clip type contained within the audition, like this:

So technically Audition is a "virtual" or "dummy" clip type? 

I will exclude `Audition` from the database template.

> Or just make it seamless as the user probably doesn't care that it's an audition, they just care what clip type is contained within, and we leave out any indication that it's an audition:

Yes. Let's keep things simple. We can just print is as 

```
Compound
```

**Comment by orchetect** [comment]
> Audition is a "virtual" or "dummy" clip type?

Yeah, a surrogate clip, if you will. When you're editing a FCP project you just see the clip, and the fact that there's other versions of that clip. Audition is not all that useful to the user as a type emitted in the manifest.

> we can just print is as
>
> `Compound`

So yes, that seems like the best way to go there.

**Comment by orchetect** [comment]
Related: I've also confirmed that the audition 'surrogate' is not capable of having markers attached to it. You can only attach markers to the clip within it. Which is useful to know from a technical standpoint, but also it makes sense.

**Comment by IAmVigneswaran** [comment]
Interesting! Only in FCP, users visually see it s an audition clip. It is more like a 'surrogate' metadata / wrapper  to load the actual clips.

**Comment by orchetect** [comment]
Yes, there is an indicator that the clip contains auditions and you can switch between them. What I mean is that, in a practical sense, the user does not consider it a different clip type just because of that.

**Comment by orchetect** [comment]
Why was this bumped to 0.2.9? This was already done with 0.2.5.
