### ISSUE TITLE
Add Clip Keywords manifest field

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#63]
Add `Keywords` manifest field. See below.

**Comment by orchetect** [comment]
I like the idea of adding Caption as a marker type if we enable converting them to markers.

I don't think there's anything else new here though? No need to create summary issues. I haven't had a chance to go through the issue backlog because I need to finish developing and unit testing the new parser. Then there will be time to address all the old issues.

**Comment by IAmVigneswaran** [comment]
It is complicated to add `Clip Keywords` column? We can have this column after `Clip Name`.

I wonder if we can add the Keywords tagged within the Clip Range from the Marker position?

<img width="536" alt="Marker-Keyword-01" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/f781478e-6941-4e0d-a3f0-51959d13177a">

<img width="658" alt="Marker-Keyword-02" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/3b424ba8-3c48-4be0-b21f-9fb8312a00d3">

When Inspecting FCPXML  -

```xml
  <asset-clip ref="r2" offset="0s" name="Nature Makes You Happy" start="550912/12800s" duration="9216/12800s" tcFormat="NDF" audioRole="dialogue">
                            <adjust-colorConform enabled="1" autoOrManual="manual" conformType="conformNone" peakNitsOfPQSource="1000" peakNitsOfSDRToPQSource="203"/>
                            <keyword start="99/5s" duration="25088/12800s" value="penguin"/>
                            <keyword start="1076/25s" duration="9216/12800s" value="flower, nature"/>
                            <marker start="1082/25s" duration="100/2500s" value="Marker 37"/>
                            <keyword start="257/5s" duration="6656/12800s" value="penguin"/>
                            <keyword start="1454/25s" duration="19456/12800s" value="nature"/>
                            <keyword start="1454/25s" duration="15872/12800s" value="flower"/>
                            <keyword start="297/5s" duration="3584/12800s" value="flower"/>
                        </asset-clip>

```

Seem that the associated Keyword Tags are always above the Marker?

```xml
                            <keyword start="1076/25s" duration="9216/12800s" value="flower, nature"/>
                            <marker start="1082/25s" duration="100/2500s" value="Marker 37"/>

```

```xml
                            <keyword start="61s" duration="27648/12800s" value="birds"/>
                            <marker start="1544/25s" duration="100/2500s" value="Marker 42"/>
```

In our CSV -

<img width="146" alt="CSV-With Keywords" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/f1ed3d83-6c8a-4e7a-9b52-7176a5d5d4a8">

Those values would automatically be converted as Multi-Select types in Notion and Airtable.

User could have another layer of filtering option in their Database.

**Comment by orchetect** [comment]
I did a bit of a deep dive this past week on keywords, so yes. They are already being parsed, just not used yet. In fact I was going to open an Issue to propose adding them to the manifest but haven't had a chance yet.

We can apply similar logic for out-of-bounds keywords as we do with out-of-bounds markers.

Since keywords can apply to an entire clip or a portion of a clip, a bit of extra math is involved. As long as some portion of the keyword's range of a clip is visible from the main timeline, we would include in on the output manifest.

**Comment by IAmVigneswaran** [comment]
We can place `Clip Keywords` after `Clip Duration`.

<img width="406" alt="Clip Keywords" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/e93f571e-549a-47b9-9507-9f5f92085eeb">

**Comment by orchetect** [comment]
This was more complex than anticipated since keywords can apply to an entire clip or to a range of a clip.

I've built out the parser logic necessary to extract keywords for each marker.

One of two options are possible:
1. Respect the keyword ranges. Meaning, if a marker is placed on a clip then only keywords that contain the marker within their range will be extracted for that marker.
2. It's also possible to just take all keywords from a clip and apply them to a marker, ignoring the keyword ranges. I added this option in case we want it.

The default behavior should be Option 1, respecting the ranges. In that case, our manifest field should be called `Keywords` since it's containing keywords that only apply to the marker.

If you feel Option 2 is the better way to go, then our manifest field could be called `Clip Keywords`.

**Comment by orchetect** [comment]
Also, this will be implemented in the manifest files the same way `Audio Role & Subrole` was.

For CSV/TSV it will be comma-separated list.
For JSON, it will be a string array.

**Comment by IAmVigneswaran** [comment]
> Respect the keyword ranges. Meaning, only keywords that contain the marker within their range will be extracted for that marker.

I would prefer Option 1. And I believe advance users of FCP would also prefer this way too, since it would respect the keyword ranges. But I am sure there might be cases where users might prefer Option 2.

Should we have flag called `--keyword-range` with `marker` (default) or `clip` options?

> Also, this will be implemented in the manifest files the same way Audio Role & Subrole was.
> 
> For CSV/TSV it will be a comma-separated string.
> For JSON, it will be a string array.
> 

Yeap. Thank you.

**Comment by orchetect** [comment]
> Should we have flag called `--keyword-range` with `marker` (default) or `clip` options?

Trying to avoid flag creep if possible. We can add it if there's a strong need for it later.

I'd maybe call it `--keywords-source` with `inRange` or `allOnClip` as arguments.

**Comment by IAmVigneswaran** [comment]
> Trying to avoid flag creep if possible. We can add it if there's a strong need for it later.

Noted!

**Comment by orchetect** [comment]
I posted an alpha release for testing: https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.6-alpha1

Please give it a try and check all the profiles to make sure they contain the new manifest field and its contents is correct.

**Comment by IAmVigneswaran** [comment]
Some observations, 

@samplue's CSV.

<img width="887" alt="Clip Keywords" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/7a12a942-93cd-4da5-8f5d-75776a096819">

There is a "risk" of having extremely long keywords. Users might have input keywords with long characters. While it is users's choice and workflow, there might be potential issue (when parsing and various edge cases) when uploading keywords with `Spaces`,  `,` and `.`. 

Truncation occurs (depends on column width) in Notion and Airtable.

Notion
<img width="438" alt="Notion-Long-Keywords" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/741bb7d4-67b1-4fd8-9df1-abae8d16f3c0">

Airtable
<img width="306" alt="Airtable-Long-Keywords" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/b15f8cb6-b9b4-42dc-8e83-1193187644e3">

There is also some limit for property values within Notion. I can't find the information for Airtable.
https://developers.notion.com/reference/request-limits#size-limits

<hr>

I wonder does it make sense to do the following:
1. Convert all `Spaces` and `,` `.` to `-`.  
 **Example:** - `vfx - cg helicopter` to `vfx-cg-helicopter`. `3. free line of fire` to `3-free-line-of-fire`
That way all options listed in Notion or Airtable would be more neat, consistency and easier to sort and also not to clutter the interface.

2. Make all of the keywords in lower case. Again for consistency.

3. Limit to 99 keywords.

4. Any keyword that has more than 99 characters will be ignored and not included in the CSV/JSON.

It also encourages users to be more precise and optimal with their keywords.

**Comment by orchetect** [comment]
> 1. Convert all `Spaces` and `,` `.` to `-`.

Unless there are known issue(s) with specific illegal characters, users probably don't want us to sanitize the keyword text. MarkersExtractor's job is primarily to extract data, it shouldn't be making a lot of decisions or subjective assumptions on how to format it.

> 2. Make all of the keywords in lower case. Again for consistency.
> 3. Limit to 99 keywords.
> 4. Any keyword that has more than 99 characters will be ignored and not included.

You're free to alter the data in Marker Data as much as you like of course, but the CLI tool should keep data unmodified as much as possible.

**Comment by IAmVigneswaran** [comment]
Test Library.

[Keywrods-Test.fcpbundle.zip](https://github.com/TheAcharya/MarkersExtractor/files/15123391/Keywrods-Test.fcpbundle.zip)

I am not sure is this a issue or not.

In this test example - `Penguin` Keyword is not used for the clip range.

<img width="687" alt="Keyword-Test-01" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/f0eb763c-cd22-456f-97a2-2701ec421ab7">

However, `Penguin` keyword is added.

<img width="1323" alt="Keyword-Test-02" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/aadbe241-fa5a-4868-ba87-0939ed39cd62">

**Comment by IAmVigneswaran** [comment]
We should also include `Clip Keywords` for the `--label` burn-ins.

**Comment by orchetect** [comment]
> We should also include `Clip Keywords` for the `--label` burn-ins.

Certainly possible but there should be a hard character count limit (100?) for it so extremely long keyword lists don't create a huge mess on thumbnail images.

**Comment by orchetect** [comment]
> Penguin Keyword is not used for the clip range.

Not sure what's going on there without more in-depth tests.

I also noticed that some keywords are being repeated in the manifest. I should add a de-duplication step to the keyword extraction.

**Comment by IAmVigneswaran** [comment]
> Certainly possible but there should be a hard character count limit (100?) for it so extremely long keyword lists don't potentially create a huge mess on thumbnail images.

Yes. 99 or 100 character limit would be ideal.

**Comment by orchetect** [comment]
Actually, it's already possible. `--label clipKeywords`

But I will add a max char limit.

**Comment by orchetect** [comment]
<img width="166" alt="keyword-formatting" src="https://github.com/TheAcharya/MarkersExtractor/assets/11605557/2910ffd4-8367-4780-8ddc-5d2ed679aabf">

I am now trimming leading and trailing whitespace, removing duplicates, and sorting alphabetically. This cleans up the keyword list a lot.

**Comment by orchetect** [comment]
I have a theory regarding the spurious `penguin` keyword appearing.

In the keyword extraction function, if there is an error when reading a keyword's range, the keyword is included by default as a failsafe. For that first marker, "Yellow Flower", one of the clip regions that has the `penguin` keyword is outside of the used area of the clip. Maybe it's hitting an error there.

**Comment by orchetect** [comment]
Ok I believe I have fixed the spurious keyword extraction.

<img width="1054" alt="keywords-csv" src="https://github.com/TheAcharya/MarkersExtractor/assets/11605557/ecb8103b-5399-4a03-a691-f0203adc2038">

**Comment by orchetect** [comment]
I posted a new alpha release for testing: https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.6-alpha2

**Comment by IAmVigneswaran** [comment]
> I posted a new alpha release for testing: https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.6-alpha2

Just tested on couple of timelines, everything seems to be working as expected.
