### ISSUE TITLE
Remove `Clip Filename` manifest field

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#65]
The `Clip Filename` output manifest field actually presents a number of issues and I would like to remove it. It's simple for basic asset clips that only have one video file.

However compound clips, sync clips, and multicam clips can contain clips using more than one video file. In that case it would not be clear what file to include for this field.

**Comment by IAmVigneswaran** [comment]
User would find `Clip Name` for more useful. 

If they are using sync clips, and multicam clips, the `Clip Filename` would be empty most of the time.

Example - 

https://www.youtube.com/watch?v=A1Diuxkf8E4

**Comment by orchetect** [comment]
Yes indeed.

(btw, I have been using "manifest file", "output manifest", "export manifest" to refer to CSV or JSON files in the codebase for a while as it's more generic)

**Comment by orchetect** [comment]
Done. Will be in 0.2.5.

**Comment by IAmVigneswaran** [comment]
Just tested. `Clip Filename` column is removed

We can close this for now.
