### ISSUE TITLE
Result file changes

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#67]
The following modifications to the result file (formerly known as 'done' file) are needed:

- [x] Add key name `profile` containing the profile name as the value
  Referenced from: https://github.com/TheAcharya/MarkerData/issues/9
- [x] Add key name `exportFolder` containing the final output path of the extracted files
- [x] Change `--done-filename` CLI option (`MarkersExtractor.doneFilename`) to `--result-file-path` (`MarkersExtractor.resultFilePath`) which can accept a full path.
  That way shell tools can know where to find the done file and in turn it can tell them where the final output folder is.
  Referenced from: https://github.com/TheAcharya/MarkerData/issues/16
- [x] Remove `--create-done-file` flag as it will be redundant with the `--result-file-path` option. If `--result-file-path` is provided, it implicitly means that a done file should be created. If not supplied, no done file is created.

**Comment by orchetect** [comment]
I'm going to change 'Done File' nomenclature to 'Export Result'. It's more descriptive.

Some of the key names will change to be more consistent and descriptive as well.

**Comment by orchetect** [comment]
This is done and will be in 0.2.6.

**Comment by IAmVigneswaran** [comment]
Will close this for now.
