### ISSUE TITLE
`MarkersExtractor.extract()` API should return result file contents as struct

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#68]
So consumers of the library don't need to interact with the result json file, the `MarkersExtractor.extract()` API should return the result file contents as a struct containing the same information.

Referenced from: https://github.com/TheAcharya/MarkerData/issues/16

**Comment by orchetect** [comment]
This is done. Will be in 0.2.6.

**Comment by IAmVigneswaran** [comment]
Thank you!

**Comment by IAmVigneswaran** [comment]
Will close this for now.
