### ISSUE TITLE
Full robust support of compound clips, secondary storyline, synchronize clips & multicam clips

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#7]
In the next or subsequent build, the tool should read and handle compound clips, secondary storyline & multicam clips.

All markers within compound clips and multicam clips will be ignored. Only Markers that reside on the main/master timeline will be parsed and processed.

**Comment by orchetect** [comment]
I would group auditions in with these.

- [ ] Compound clips
- [ ] Secondary storyline
- [ ] Multicam clips
- [ ] Auditions - #6

**Comment by IAmVigneswaran** [comment]
Forgot to add support for **Synchronize clips**.

https://support.apple.com/en-gb/guide/final-cut-pro/verc1fabc30/mac

**Comment by orchetect** [comment]
With the parser refactors, most of these should now be supported in the next release (0.2.4). Most of the infrastructure is there, just need to test and tweak.

I have yet to do tests with **sync clips** and **multicam clips** because I don't have any example projects that use them. If you have a basic sample project for each without a lot of extra stuff apart from the clip type in question, that would definitely help.

**Comment by IAmVigneswaran** [comment]
**Behaviour for Compound Clips**

Right now when testing with 0.2.4 MarkersExtractor is able to extract Marker that are within Compound Clips. 

But I think we should ignore by default Markers that are within Compound Clips. Cause Compound Clips can have umpteen number of nested Compound Clips with each Compound Clips. It can will get complex.

We should only parse the Marker that are on the any main timeline. 

If user want so extract the markers from within the Compound Clip, he/she would just double-click the Compound Clip and export that particular timeline. Again, any markers that nested within any Compound Clips of that timeline would be ignored.

What do you think?

**Comment by orchetect** [comment]
> we should ignore by default Markers that are within Compound Clips
> We should only parse the Marker that are on the any main timeline.

I agree, just like only using markers on active auditions and not alternative auditions.

This was very easy with the clip type filtering I built in, and is now done. Will be in 0.2.5.

Example with nested compound clips:

Main project timeline. Contains two compound clips.

![main-timeline](https://github.com/TheAcharya/MarkersExtractor/assets/11605557/e9c8af67-5030-4082-8749-178f1122a2f0)

Title Compound Clip contains only a Basic Title, with a marker on it.

![title-compound-clip](https://github.com/TheAcharya/MarkersExtractor/assets/11605557/bf3552b2-8f1e-46a9-b570-16e847fb979b)

Clouds Compound Clip contains a Clouds generator with a marker on it, and after it the same Title Compound Clip is added with a marker on it, as well as the marker that is contained inside of it (now 2 layers deep).

![clouds-compound-clip](https://github.com/TheAcharya/MarkersExtractor/assets/11605557/a7009e54-08e5-46ae-b29c-aa4c6e125539)

Technically there are 5 total markers in the project then.

Output of the CSV only contains only the one marker on the main timeline:

![csv](https://github.com/TheAcharya/MarkersExtractor/assets/11605557/eecc79cf-7311-43c5-b83a-ece326612880)

**Comment by orchetect** [comment]
Actually I realized that [big project I tested today](https://github.com/TheAcharya/MarkersExtractor/issues/37#issuecomment-1823610099) has sync clips and multicam clips, and markers extract fine, with correct timecodes, names, clip types, etc.

What we need to do now is test roles to see if they are parsing as expected.

**Comment by orchetect** [comment]
I'm going to close this, as marker parsing seems to be working on all clip types. We just need to test that roles are being parsed correctly, and we can open a new issue if there are any problems with roles.
