### ISSUE TITLE
Nonexistent `Role` member used on struct `DAWFileKit.FinalCutPro.FCPXML`

### ISSUE THREAD

**Issue by milanvarady** [TheAcharya/MarkersExtractor#70]
### Bug Description, Steps to Reproduce, Crash Logs, Screenshots, etc.

Hi, I updated to version 0.2.6, but when I compile I get this error message: 

> 'Role' is not a member type of struct 'DAWFileKit.FinalCutPro.FCPXML'

The problem is in the `FCPXMLMarkerExtractor.swift` at line 255 `FinalCutPro.FCPXML.Role`

```swift
func getClipRoles(_ marker: FinalCutPro.FCPXML.Marker) -> MarkerRoles {
            ...
            func handle(role: FinalCutPro.FCPXML.Role) { // Here
            ...
```

**Comment by orchetect** [comment]
It's because DAWFileKit was set to main branch and its API is changing. Just pull main branch of MarkersExtractor until I can release 0.2.7.

**Comment by orchetect** [comment]
0.2.7 is up.

**Comment by milanvarady** [comment]
Thanks! It compiles now.
