### ISSUE TITLE
Adding Caption to Naming Mode options

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#71]
Right now we have `--id-naming-mode <projectTimecode, name, notes>`. 

We can have the `caption` as the 4th naming mode.

**Comment by orchetect** [comment]
Can you explain what this is supposed to do? We already have the ability to use captions as markers and this feels like a conflict.

**Comment by IAmVigneswaran** [comment]
> Can you explain what this is supposed to do? We already have the ability to use captions as markers and this feels like a conflict.

Okay, I just realise, when using `Name` option, users can utilise captions's value as image file name.

<img width="329" alt="Caption   Markers" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/c9416567-3642-48ba-a633-4da345d408ea">

[Caption-Test.fcpbundle.zip](https://github.com/TheAcharya/MarkersExtractor/files/15088477/Caption-Test.fcpbundle.zip)

Not sure if this is a downside, if users want to mix `Timecode` as Image Filenames for regular markers and captions's value as image file name, would not be possible.

**Comment by IAmVigneswaran** [comment]
A related issue, there is a conflict when using both  `--markers-source markersAndCaptions --id-naming-mode notes`.

Our tool throws this error.

```
Extracting Markers and Captions...
5%
Error: Empty marker ID encountered. Markers must have valid non-empty IDs.
```

How should we approach this?

**Comment by orchetect** [comment]
I think we limit the number of options. If a feature requires a lot of pre-planning or workarounds for a user, it probably shouldn't be an option.

**Comment by IAmVigneswaran** [comment]
> This isn't a related issue, it's a separate issue.
> 
> I think we limit the number of options. If a feature requires a lot of pre-planning or workarounds for a user, it probably shouldn't be an option.

I think we can we grey out `Notes` option, when Marker Source is set to Marker and Captions or Captions in Marker Data.
