### ISSUE TITLE
Rename Marker Icons Filenames

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#72]
For file organisation let's have a prefix for each icon image with `icon-x.png`

`icon-caption.png`
`icon-marker.png`
...
etc.

That way when we are sorting files alphabetically in finder, all icon files would appear together.

**Comment by orchetect** [comment]
Done, will be in 0.2.8.

New filenames for icons:

```
icon-caption.png
icon-marker.png
icon-marker-chapter.png
icon-marker-todo-incomplete.png
icon-marker-todo-complete.png
```

**Comment by IAmVigneswaran** [comment]
Will close this for now.
