### ISSUE TITLE
Profiles & Formats (CSV)

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#74]
Continuing the discussion here from https://github.com/TheAcharya/MarkersExtractor/issues/21#issuecomment-1833807840

We can have Export Profile name called `CSV`.

While both of our Notion and Airtable Profiles' manifest file would be in .json file format, it would be great if we can have a dedicated profile called `CSV`.

It would allow users to import the data into spreadsheet applications like, Excel, Numbers, Google Sheet or Libreoffice.

We can use the current Airtable's CSV profile for `CSV` profile. It would not have `Icon Image` column and it would not generate the Notion icons.

I am not sure if `.csv` or `.tsv` would make the best sense.

https://stackoverflow.com/questions/11130120/choosing-between-tsv-and-csv

**Comment by orchetect** [comment]
It's pretty easy to support both TSV and CSV. I've done it in many other apps.

There is actually more to the formats than just using a tab or comma as column delimiters. There's additional formatting considerations. So whenever reading or writing these formats, never parse it manually. Always use a library that is designed to read and write. And of course same principle applies to JSON.

**Comment by orchetect** [comment]
Once we have a CSV profile it should probably become the default profile since it's the most vanilla / common format.

**Comment by IAmVigneswaran** [comment]
> Once we have a CSV profile it should probably become the default profile since it's the most vanilla / common format.

Yes. CSV profile can become the new default.

**Comment by orchetect** [comment]
Done. CSV and TSV profiles will be in 0.3.1.

I have also fixed CSV encoding so fields that might contain double-quotes (`"`) and/or commas (`,`) encode correctly.

**Comment by IAmVigneswaran** [comment]
Notion is still the default profile in 0.3.1?

**Comment by orchetect** [comment]
Yeah, missed that. I'll update the new issue when it's changed.
