### ISSUE TITLE
Automatic Bypass of Media

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#77]
Currently we have an explicit `--no-media` switch. 

Does it also make sense to have a behaviour where when there is no accompanying media, MarkersExtractor would automatically use `--no-media`. 

We can have a short delay to check if media is present in the same folder? If no, `--no-media` behaviour would step in.

**Comment by orchetect** [comment]
Actually I was thinking about this exact thing weeks ago.

We should remove the `--no-media` flag and just post a warning to the log that no media was found, then continue with extraction as normal.

**Comment by IAmVigneswaran** [comment]
> Actually I was thinking about this exact thing weeks ago.
> 
> We should remove the `--no-media` flag and just post a warning to the log that no media was found, then continue with extraction as normal.

Yes. Let's remove it.

**Comment by orchetect** [comment]
This is done. Will be in 0.3.0.

**Comment by orchetect** [comment]
Actually, I realized that there is still a use case for having the `--no-media` CLI flag.

Even just during testing it's useful to skip thumbnail generation even when a media file does exist.

I've added the flag back.

**Comment by IAmVigneswaran** [comment]
Noted!
