### ISSUE TITLE
Remove support for out-of-bounds markers (CLI flag and log warnings)

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#78]
As I've gotten intimately familiar with how Final Cut Pro works and the inner workings of FCPXML, a few things have become more clear.

One of them is out-of-bounds markers.

A quick recap: They only happen when a marker exists on a clip and then the user resizes the clip to be smaller. The marker is not deleted in their session. Final Cut Pro just hides it. If the clip is resized larger, the marker becomes visible again.

In fact, as far as users are concerned, they don't exist any more. And most people will forget they were even there.

1. The user does not see them on their main timeline, and I don't see a use case for having a CLI flag to include them.
2. It's pointless to post a console message about them, which may just confuse users because it's not an error, and they never expected to extract them any way since they don't see them on the main timeline.

**Comment by IAmVigneswaran** [comment]
> In fact, as far as users are concerned, they don't exist any more. And most people will forget they were even there.
> 
> 1. The user does not see them on their main timeline, and I don't see a use case for having a CLI flag to include them.
> 2. It's pointless to post a console message about them, which may just confuse users because it's not an error, and they never expected to extract them any way since they don't see them on the main timeline.

We can just remove the CLI flag and log message. 

Hence from the user's perspective what they see on their timeline, is what they get. If they trim a clip with a marker, they will not see it. 

But let's keep the logic and function internally should there be a request to bring it back?

**Comment by orchetect** [comment]
This is done. Will be in 0.3.0.

**Comment by IAmVigneswaran** [comment]
Will close this, since this addressed.
