### ISSUE TITLE
Ability to use Captions as Markers

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#8]
It would be beneficial and awesome if we can use Captions as Markers.

The tool would have 2 modes. The default would be `markers`. In `captions` mode, the tool will ignore and bypass all markers and parse captions as markers. All GIFs or Still will be exported from the starting timecode of each caption.

<img width="784" alt="Caption Markers" src="https://user-images.githubusercontent.com/118706051/207224933-c8f5a934-81bf-4515-8fb4-6b3a9b777c52.png">

This option could be used:
```
OPTIONS:
  --Marker-Mode <markers,captions> (default: markers)
```

**Comment by orchetect** [comment]
In the recent DAWFileKit refactors, it's not easy to parse captions. So this should be pretty easy to add.

**Comment by IAmVigneswaran** [comment]
@orchetect 

There are numerous FCP users who uses Captions as Makers. Since you are able to add multiple "lanes" of Captions, it offer additional layers of flexibility for users.

**Comment by orchetect** [comment]
Would we want a flag to opt-in to simply convert captions into markers? Or is it still important to have the exclusive captions or markers behavior you described earlier in the thread?

**Comment by IAmVigneswaran** [comment]
> Or is it still important to have the exclusive captions OR markers (but not both) behavior you described earlier in the thread?

I think this makes the most sense.

OPTIONS:
`  --Marker-Mode <markers, captions, both> (default: markers)`

With Marker Data,

We can have Dropdown selection in the General Setting Panel.

**Comment by orchetect** [comment]
Since captions can be created in multiple languages, it's possible to have more than one caption at the same timecode. In that case should we just use the first caption for that timecode?

If users are using captions as markers then they are unlikely to be using them as **actual closed captions** and won't be using multiple languages.

**Comment by IAmVigneswaran** [comment]
> Now that I think of it, the same question could be asked about markers themselves. If we parse more than one marker for any given timecode, should just the first marker be used and any overlapping ones discarded? In that case, we'd apply the same rule for captions, since we will be essentially converting captions to markers.

I believe we have already address this issue? #9 https://github.com/TheAcharya/MarkersExtractor/issues/9#issuecomment-1367801537

> In that case should we just use the first caption for that timecode?

How about this? MarkersExtractor will only look for caption track that have this "**Markers**" name.

<img width="682" alt="Captions" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/a8d9ece5-fb5d-4edc-9a0c-370c46ea171d">

MarkersExtractor will ignore another other caption track? That way, users can have Real captions for language and they can also have an additional caption track call "**Markers**"? They can only have 1 captions track with "**Markers**". Furthermore FCP does not allow users to create a captions track with the same name.

<img width="855" alt="Captions-Text" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/e864555f-cec3-447f-96d2-cdc492612afb">

What do you think?

**Comment by orchetect** [comment]
> > If we parse more than one marker for any given timecode [...]
>
> we have already address this issue

Of course - makes sense. My brain is cooked after two weeks of refactoring and forgot about that.

> MarkersExtractor will only look for caption track that have this "Markers" name.
> That way, users can have Real captions for language and they can also have an additional caption track call "Markers"?

That's a good idea. However, there's no need to constrain it to an arbitrary hard-coded name like "Markers".

I would suggest default behavior when converting captions to markers is to just use all captions. After converting to markers, they will unique their IDs the same way markers already do. Then at least if the user wants that, they have it.

If the user then wants to specify a specific caption role name then we can provide a CLI flag for that:

`--caption-role Markers`

**Comment by IAmVigneswaran** [comment]
> That's a good idea. However, there's no need to constrain it to an arbitrary hard-coded name like "Markers".
> 
> I would suggest default behavior when converting captions to markers is to just use all captions. After converting to markers, they will unique their IDs the same way markers already do. Then at least if the user wants that, they have it.

Noted! Makes sense. 

Since MarkersExtractor's default behaviour always extracts markers, users would require some tiny setup before they want to use caption as markers. I can write up some recommended methods in the user guide.

> If the user then wants to specify a specific caption role name then we can provide a CLI flag for that:
> 
> `--caption-role Markers`

We can have a field in General Settings for users to enter the name of Caption Role.

**Comment by orchetect** [comment]
> tiny setup before they want to use caption as markers

At most it would be two steps.

1. Opt-in to using captions.

   `--markers-source <markers, captions, markersAndCaptions> (default: markers)`

2. If you want to filter converted captions, supply the optional flag. It has no effect if captions are not enabled in the first step.

   `--caption-role MyMarkersRoleName`

> I can write up some recommended methods in the user guide

Sure, always useful to help guide users.

**Comment by IAmVigneswaran** [comment]
If I understand correctly, 

`--caption-role` would only be active or usable if `captions` or  `markersAndCaptions` in `--markers-source` ?

**Comment by orchetect** [comment]
Yes exactly. `--caption-role` would not implicitly convert captions to markers.

**Comment by IAmVigneswaran** [comment]
Question - 

For  `--markers-source <markers, captions, markersAndCaptions>`, would setting `captions` or `markersAndCaptions` have any impart or conflict with `--id-naming-mode`?

Also in both `captions` or `markersAndCaptions` mode, if captions have identical values, there would be `-number ` suffix appended at the end of the name?

**Comment by orchetect** [comment]
The first half of this is now implemented and unit tested, and will be in 0.2.7:

- `--markers-source <markers, captions, markersAndCaptions>`

The second part still will be implemented soon:

- `--caption-role <role>`.

**Comment by IAmVigneswaran** [comment]
> I realized that since captions are treated by FCP as global to the main timeline, it's not "possible" for them to be out of bounds.

Yes, Since caption have their own dedicated "lane" in the timeline unlike markers.

> Also, because captions are anchored to a clip, they actually have a Clip Type (Asset, Sync, Compound, Multicam, Title, etc.) just like markers do.

https://support.apple.com/guide/final-cut-pro/vere399dab5e/mac

Captions are always connected clips. Captions can also be connected to other connected clips.

**Comment by orchetect** [comment]
Since captions are a new "marker" type for the manifest, they also get an icon image. I assigned the standard marker image for now, but if you want to come up with a different color for chapters we can add it.

![caption-icon](https://github.com/TheAcharya/MarkersExtractor/assets/11605557/0b6f8aee-d235-468b-8d0a-8119fa654012)

**Comment by IAmVigneswaran** [comment]
I will design one specific for caption type by tomorrow.

**Comment by IAmVigneswaran** [comment]
Done.

Updated Marker Set. 

Caption's filename is `marker-caption.png`.

[markers.zip](https://github.com/TheAcharya/MarkersExtractor/files/13468814/markers.zip)

**Comment by orchetect** [comment]
Are you sure the caption marker will be visible on whatever platforms you're using it?

**Comment by IAmVigneswaran** [comment]
> Are you sure the caption marker will be visible on whatever platforms you're using it?

I have made a new version. 

[marker-caption.png.zip](https://github.com/TheAcharya/MarkersExtractor/files/13495065/marker-caption.png.zip)

Looks better now?

<img width="339" alt="Notion Icon" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/d7cfa55b-c32c-4807-a490-630a7f4509bb">

**Comment by orchetect** [comment]
New caption icon will be in 0.2.8.

**Comment by orchetect** [comment]
Since there is overlap with the caption role filter and general marker filters, I have suggested a unified approach in #57.

**Comment by IAmVigneswaran** [comment]
Will close this for now.
