### ISSUE TITLE
Bug in Timeline with Mixed Frame Rate Clips

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#81]
Steffan,

I notice a bug in frame / image extraction of 23.98 video file. For some reason, the marker position is not respected. There is an offset of 23 frames back.

In Timeline
<img width="998" alt="Marker-Position" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/bef39f22-8ded-4298-abae-f52ded6e97d5">

Extracted Image
![23_98_V1_00_00_53_15](https://github.com/TheAcharya/MarkersExtractor/assets/118706051/8cb6dcaa-68cb-4710-851a-fa30eb8b6e7f)

It does not happened to all markers but randomly on some markers.

**Comment by orchetect** [comment]
See if you can narrow down the symptoms. Are there mixed frame rates in the project? What clip type is it and what is its frame rate? What is the project frame rate?

**Comment by IAmVigneswaran** [comment]
> Are there mixed frame rates in the project?

Yes.

> What clip type is it and what is its frame rate?

The Clip Type is on Audition. The Frame Rate of the original clip is 25 FPS.

<img width="215" alt="audition-clip-type" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/75142ed6-2b28-485e-991a-82f85fda3f1c">

> What is the project frame rate?

23.98 FPS.

The offset bug only occur on a clip that has an original 25 FPS as per my sample timeline.

<img width="537" alt="offset-bug" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/8c296141-00ad-45ff-937e-d8ed6c601b98">

**Comment by IAmVigneswaran** [comment]
Second Example - With Project Frame Rate 60 FPS. Having a mixed clips of 29.97 and 23.98. 

It occurs for some markers.

<img width="573" alt="60FPS-Timeline" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/064f58cf-7af3-45b4-b705-8f7311416a70">

**Comment by orchetect** [comment]
I'm not able to reproduce this. Can you email me the projects for both of these examples?

**Comment by orchetect** [comment]
Ok I've confirmed the issue with the sample projects. Will see if I can get a fix out this week.

**Comment by orchetect** [comment]
On analyzing the FCPXML, the numbers just don't make sense.

I'll have to shelve this and come back to it because I just can't see how it's coming up with the time values it's using. (And I've done a lot of mixed-framerate parsing already with FCPXML and everything has made sense so far.)

**Comment by latenitefilms** [comment]
Unrelated, but also something to keep in mind... FCPX doesn't do any DTD validation on export, so FCPX can itself export invalid FCPXML:

https://github.com/CommandPost/FCPCafe/issues/314

**Comment by orchetect** [comment]
> FCPX can itself export invalid FCPXML

Yes true. This isn't a DTD violation thankfully, it's the actual time value math that isn't adding up. And yet importing the XML back into FCPX restores everything correctly. So the answer is somewhere, just needs to be found.

**Comment by latenitefilms** [comment]
Can you share a FCPXML with the issue?

**Comment by orchetect** [comment]
I think I've cracked the nut. FCPX is doing frame rate scaling in a way I didn't anticipate.

**Comment by orchetect** [comment]
I think I've cracked the nut. FCPX is doing frame rate scaling in a way I didn't anticipate.

ie: In a project at 23.98 fps, an `asset-clip` which references media at 25fps may look like this:

```xml
<asset-clip ref="r6" name="TestVideo2" duration="646646/24000s" format="r7" tcFormat="NDF" audioRole="dialogue">
    <conform-rate srcFrameRate="25"/>
    <marker start="177/25s" duration="1001/24000s" value="Audition 1"/>
    <marker start="344/25s" duration="1001/24000s" value="Audition 2"/>
    <marker start="22s" duration="1001/24000s" value="Audition 3"/>
</asset-clip>
```

"r6" is a `25fps` asset, "r7" is a "FFVideoFormat1080p25" `format`.

Time values within the `asset-clip` must be scaled based on source and destination frame rates.

```xml
<marker start="177/25s" ...
```

`177/25s` here cannot be used as a literal value (7.08 seconds) because of the presence of an implicitly-enabled `conform-rate`. Instead, for children of the `asset-clip`'s local timeline, their time values seem to need scaling using the following formula:

`
start x PFD / MFD
`

where PFD is the project frame duration (`1.001/24`) and MFD is the media frame duration (`1/25`).

Then the result is a correct literal real-time value of 7.382375 seconds which produces the correct sequence timecode position.

**Comment by orchetect** [comment]
I have made the corresponding refactors and unit tests in DAWFileKit.

The fix will propagate to MarkersExtractor 0.3.2.

**Comment by IAmVigneswaran** [comment]
Just tested. I am getting some strange results. In our `Marker FPS Test` library, I have tested with the `60_V1` timeline.

The timecode does not line up.

<img width="667" alt="60FPS-Error" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/ba250153-dfcf-4fd2-bce8-a6414c89c485">

<hr>

But when testing with the `23.98_V1` timeline; the timecode is correct and they line-up.

<img width="581" alt="23-98-FPS-Data" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/c10c7812-e599-430e-8396-d76736b72ae4">

**Comment by orchetect** [comment]
Ok I will pull open that project and see what's going on.

**Comment by orchetect** [comment]
After spending all evening hacking at this, it appears the frame rate scaling is way more nuanced than it first seemed.

The scaling is not a simple formula between two rates, but varies depending on the nature of the individual rates and how they relate to each other.

I've refactored DAWFileKit to resolve the issues with both sample projects above (23.98_V1 and 60_V1) but they only involve a handful of rates. It's a step forward but not a universal fix just yet.

The chart found [here](https://developer.apple.com/documentation/professional_video_applications/fcpxml_reference/story_elements/conform-rate) is actually not very useful and may be misleading, as I am finding that there is little or no correlation with real-world results which I am implementing and verifying in the library. (For example, the chart indicates that no scaling happens between 23.98 and 60 but manual verification shows that is not true in practise.) For that reason I will need to manually verify and unit test as many rate combinations as possible.

**Comment by orchetect** [comment]
Thus far I've been able to implement correct scaling and unit tests for the following:

- Project @ 23.98 containing media at 23.98 and 29.97
- Project @ 24 containing media at 23.98 and 29.97
- Project @ 29.97 containing media at 23.98 and 29.97
- Project @ 29.97 drop containing media at 23.98 and 29.97
- Project @ 30 containing media at 23.98 and 29.97
- Project @ 59.94 containing media at 23.98 and 29.97
- Project @ 60 containing media at 23.98 and 29.97

In theory, the reciprocals should also be functional (ie: for any given test above, swap project rate with any of the containing media rates)

**Comment by IAmVigneswaran** [comment]
Seems to be working with our FPS testing timelines. I will close this issue for now.

We can revisit or open this in future if any users reports on this issue.

Thank you Steffan!

**Comment by latenitefilms** [comment]
Did you try putting 25.0fps clips in a 24.0fps timeline?

**Comment by IAmVigneswaran** [comment]
@latenitefilms Thanks for pointing out.

@orchetect Looks like 25FPS clips on 24FPS Timeline is not supported yet.

<img width="533" alt="25 Clip on 24 Timeline - 01" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/be03cb63-5eb5-4ec8-9641-ebb35751d427">

<img width="1038" alt="25 Clip on 24 Timeline- 02" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/3982bc96-a99e-455d-a709-d4364dcca051">

**Comment by orchetect** [comment]
Not all rate combinations have been tested for scaling yet so some may be incorrect.

**Comment by latenitefilms** [comment]
I've tried to get my head around a 25fps clip on a 24fps timeline, but even with this simple example (at the bottom of the page), I'm left very tired and confused:

https://fcp.cafe/developers/fcpxml/#getting-source-timecode

**Comment by orchetect** [comment]
In DAWFileKit it's just a scaling factor I need to add. Doesn't take long to work it out but I need to create a test project first and add it to the unit tests which takes a while.

**Comment by orchetect** [comment]
In DAWFileKit it's just a scaling factor I need to add. Doesn't take long to work it out but I need to create a test project first and add it to the unit tests which takes a while.

**Comment by latenitefilms** [comment]
Yeah, the only reason I stumbled across this is because I was looking at your [`_fcpConformRateScalingFactor`](https://github.com/orchetect/DAWFileKit/blob/610f2bdb243f239c4d59f24327269dafefda35a5/Sources/DAWFileKit/FinalCutPro/FCPXML/XML/FCPXML%20Time%20and%20Frame%20Rate%20Parsing.swift#L275C17-L275C45) code.

You did have this:

```swift
case .whole: // 24, 25, 30, 60
            switch timelineFrameRate.compatibleGroup {
            case .ntscColor: 
                return t / m // works for 23.98 timeline -> 25 media
```

...but `t / m` doesn't seem to work for 24.0 timeline -> 25.0 media.

**Comment by orchetect** [comment]
24 → 25 would be `.whole` to `.whole` which currently returns a nil scaling factor. That's where I need to add special cases.

**Comment by orchetect** [comment]
> `t / m` doesn't seem to work for 24.0 timeline -> 25.0 media

Just added unit test. Incidentally `t / m` is the correct solution on my end. But it may be that your methods aren't taking all calculations into account in the chain. Lots of aggregate variables.

I'll push a fix soon that adds 24 t/l with 25 media soon.

**Comment by latenitefilms** [comment]
Ah, interesting! I actually tried with DAWFileKit and forced the calculation `t/m`, but must have made a mistake somewhere.

I think maybe the issue with the FCP Cafe post is that I'm basing things off the seconds value, but maybe it needs to rounded up to the nearest actual video frame?
