### ISSUE TITLE
Rename CLI executable to `markers-extractor`

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#86]
Just a suggestion that we rename the executable file for the CLI from `markers-extractor-cli` to `markers-extractor`. The `cli` portion is redundant and needlessly verbose.

Only the built executable name would be changed.

The zip filename and installer pkg filename can remain the same as before, as it's useful for `cli` to be indicated.

**Comment by IAmVigneswaran** [comment]
We can do that in the next release?

**Comment by IAmVigneswaran** [comment]
I am trying to change the executable from `markers-extractor-cli` to `markers-extractor`.

Before I make the commit, I would like to get your confirmation.

Are these the only files that needs to be edited?

https://github.com/TheAcharya/MarkersExtractor/blob/f200cc52014e95475ae982f4290702e7fb90b197/Package.swift#L17
```swift
        .executable(
            name: "markers-extractor",
            targets: ["markers-extractor"]
        )
    ],
```

```swift
        .executableTarget(
            name: "markers-extractor",
            dependencies: [
                "MarkersExtractor",
                .product(name: "ArgumentParser", package: "swift-argument-parser")
            ]
        )
```

<img width="370" alt="folder-rename" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/84476108-1af0-4059-80cc-1712593ade21">


Renaming these, won't have any impact on any other files and codebase?

Thanks.

**Comment by orchetect** [comment]
Done. Will be in 0.3.4.

**Comment by IAmVigneswaran** [comment]
> Done. Will be in 0.3.4.

I have also updated the [release_github](release_github) action.
