### ISSUE TITLE
Create Brew Release

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#87]
Continuing discussion from -

https://github.com/TheAcharya/MarkersExtractor/issues/52#issuecomment-1902787744

**Comment by IAmVigneswaran** [comment]
@orchetect I have added brew release. Check it out, if it works at your end.

```bash
$ brew install TheAcharya/homebrew-tap/markers-extractor
```
```bash
$ brew uninstall --cask markers-extractor
```

The process is semi-automatic. Each time we make a new release. We only need to press `Run Workflow` button on [here](https://github.com/TheAcharya/homebrew-tap/actions/workflows/update_version_markers-extractor.yml).

The action would automatically read the latest version number and SHA value and writes it back to the [markers-extractor.rb ](https://github.com/TheAcharya/homebrew-tap/blob/main/Casks/markers-extractor.rb)

**Comment by latenitefilms** [comment]
You should be able to do a pull request so it's just:

`brew install markers-extractor`

**Comment by IAmVigneswaran** [comment]
> You should be able to do a pull request so it's just:
> 
> `brew install markers-extractor`

They won't add or accept your tool unless your repo has enough traction.

https://docs.brew.sh/Acceptable-Casks#rejected-casks
