### ISSUE TITLE
Formatting Caption Name when listing via `RolesExtractor.extract()`

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#89]
When trying to list the roles in Marker Data's Workflow Extension, `Caption Name` is somewhat not inline with rest of our roles formatting.

Caption are listed as such.

```
Markers?captionFormat=ITT.en Caption
```

Any suggestion or way to show them in a "friendly" manner?

**Comment by orchetect** [comment]
For UI display you could just use the `role` property which would give you "Markers" in this instance.

https://github.com/orchetect/DAWFileKit/blob/efacbb222d963fa44ea37fe9e4127fc892fa2e47/Sources/DAWFileKit/FinalCutPro/FCPXML/Model/Roles/FCPXML%20CaptionRole.swift#L32-L33

If you need to include the caption format as well it requires some additional formatting.

If you want output such as `Markers (ITT.en)` then this would suffice:

```swift
let name = "\(captionRole.role) (\(captionRole.captionFormat))"
```

**Comment by IAmVigneswaran** [comment]
https://github.com/TheAcharya/MarkerData/issues/21#issuecomment-1963141347

Thank you!
