### ISSUE TITLE
Allow more than one marker with the same ID

### ISSUE THREAD

**Issue by orchetect** [TheAcharya/MarkersExtractor#9]
## Issue

Currently it is an error condition if two markers share the same timecode location and the entire process will abort before it begins.

This can easily happen if there are overlapping clips.

![fcp-overlapping-markers](https://user-images.githubusercontent.com/11605557/209529095-23a452b7-71c7-42f9-a41f-b1b90c262011.png)

```
Extracting markers from '/Users/stef/Dropbox/_coding/MarkersExtractor/Sample/Further FPS Test/29.97_V1.fcpxmld'
Error: Duplicate marker IDs found: ["29.97_V1_00:00:14:24", "29.97_V1_00:00:24:08"]
Program ended with exit code: 1
```

The reason is that the resulting ID ends up being identical which would result in thumbnail filename collisions, hence the abort.

These IDs are typically constructed from the project name and marker timecode for convenience to make human-readable filenames for thumbnails.

What is needed is an ID uniquing mechanism to append a sequential letter or number after the ID.

## Possible Solution 1

```
29.97_V1_00_00_14_24A
29.97_V1_00_00_14_24B

or

29.97_V1_00_00_14_24_1
29.97_V1_00_00_14_24_2

or

29.97_V1_00_00_14_24-1
29.97_V1_00_00_14_24-2

or

29.97_V1_00_00_14_24(1)
29.97_V1_00_00_14_24(2)
```

## Possible Solution 2

The IDs could entirely be replaced by randomly generated unique IDs (UUIDs) which will solve this issue, but be a regression in the sense that the thumbnail filenames essentially become gibberish and the human-readable convenience is lost.

```
37BBA720-197B-42D7-B143-96F1C498E003
0184D1F5-F5E7-4020-8DD4-BE4C04824BEA
```

**Comment by IAmVigneswaran** [comment]
Solution 1 seems like a practical approach. The tool could create a last digit suffix if marker collisions occurs. If there are no marker collisions, the tool will process as usual.

The numbers could have a zero padding. With a zero padding, it allows up to `99` which is more than adequate.
```
29.97_V1_00_00_14_24_01
29.97_V1_00_00_14_24_02
```

**Comment by orchetect** [comment]
I'd probably prefer to avoid two-digit padding as it then appears to be part of the timecode. It almost looks like subframes, which it isn't.

I think A, B, C is probably more clear and still maintains concise ordering.

**Comment by IAmVigneswaran** [comment]
It is true, that is not likely that more than 2 or 3 markers would share the same timecode.

I would prefer with the hyphens. 
```
29.97_V1_00_00_14_24-1
29.97_V1_00_00_14_24-2
```

**Comment by orchetect** [comment]
Considering that there are different naming modes:

```swift
public enum MarkerIDMode: String, CaseIterable {
    case projectTimecode = "ProjectTimecode"
    case name = "Name"
    case notes = "Notes"
}
```

A generalized uniquing method to append "-X" where X is a number starting from 1 and incrementing for each duplicate will still work well.

**Comment by IAmVigneswaran** [comment]
Yes, there are 3 naming mode. The default naming mode is `ProjectTimecode`. This is to ensure that all filenames are unique (without factoring in marker collisions). 

The other two naming modes, `Name` and `Notes` is to provide users options and flexibility. Once such example would be creating VFX IDs. In an ideal workflows and situation, users would need to exercise some discipline in ensuring all values of `Name` or `Notes` are unique. It might not happen all the time. But, I will instruct the users about this in the final user guide.

Would it be possible in implementing an error correction logic? If there are identical or duplicate values for `ProjectTimecode`, `Name` and `Notes` the tool would just add "-X" to the end of the **Marker ID** and **Image Filename** like you mentioned.

**Comment by orchetect** [comment]
> Would it be possible in implementing an error correction logic? If there are identical or duplicate values for ProjectTimecode, Name and Notes the tool would just add "-X" to the end of the Marker ID and Image Filename like you mentioned.

That's what I'm suggesting.

Are you saying there is a use case where you would **want** to enforce unique names? My assumption is that we can employ this uniquing method no matter what the naming mode is.

**Comment by IAmVigneswaran** [comment]
> That's what I'm suggesting.

Yes. We are on the same page!

> Are you saying there is a use case where you would want to enforce unique names at input?

What I am saying is, we can still implement the error correction logic. And if there are duplicates, the append would occur. But if the user wants to 100% ensure in having their own unique names, they can pick `Name` or `Notes` mode. But regardless the error correction logic will always take place.

**Comment by orchetect** [comment]
I feel like uniquing logic could be enabled by default regardless of the naming mode.

Perhaps a CLI flag like `--enforce-unique-names` could bypass the logic and fail out like the current behavior if it encounters any duplicates.

**Comment by IAmVigneswaran** [comment]
> I feel like the "-X" uniquing logic could be enabled by default regardless of the naming mode.

Yes. It should be enable by default.

> Perhaps a CLI flag like` --enforce-unique-names` could bypass the logic and fail out like the current behavior if it encounters any duplicates.

That could work. Perhaps the CLI could also print out any duplicates in the log file, not just fail out?

**Comment by orchetect** [comment]
This is now implemented by default.

<img width="539" alt="id-uniquing" src="https://user-images.githubusercontent.com/11605557/210052608-293b3cf7-6a63-47e1-99b4-00a062ed333c.png">

The log still leaves a message that there are non-unique IDs but they will be uniqued:

```
Extracting markers from "/Users/stef/Dropbox/_coding/MarkersExtractor/Sample/Further FPS Test/29.97_V1_withDupeMarkers.fcpxmld".
Duplicate marker IDs found which will be uniqued: ["29.97_V1_00:00:14:24", "29.97_V1_00:00:24:08"]
Found project media file "/Users/stef/Dropbox/_coding/MarkersExtractor/Sample/Further FPS Test/29.97_V1.m4v".
Generating CSV with PNG images into "/Users/stef/Desktop/me-cli-output/29.97_V1 2022-12-30 12-50-43".
Exporting marker icons.
Generating PNG images for markers.
Creating "done.json" done file at "/Users/stef/Desktop/me-cli-output/29.97_V1 2022-12-30 12-50-43".
Done!
```

**Comment by IAmVigneswaran** [comment]
> This is now implemented by default.
> 
> <img alt="id-uniquing" width="539" src="https://user-images.githubusercontent.com/11605557/210052608-293b3cf7-6a63-47e1-99b4-00a062ed333c.png">
> 
> The log still leaves a message that there are non-unique IDs but they will be uniqued:
> 
> ```
> Extracting markers from "/Users/stef/Dropbox/_coding/MarkersExtractor/Sample/Further FPS Test/29.97_V1_withDupeMarkers.fcpxmld".
> Duplicate marker IDs found which will be uniqued: ["29.97_V1_00:00:14:24", "29.97_V1_00:00:24:08"]
> Found project media file "/Users/stef/Dropbox/_coding/MarkersExtractor/Sample/Further FPS Test/29.97_V1.m4v".
> Generating CSV with PNG images into "/Users/stef/Desktop/me-cli-output/29.97_V1 2022-12-30 12-50-43".
> Exporting marker icons.
> Generating PNG images for markers.
> Creating "done.json" done file at "/Users/stef/Desktop/me-cli-output/29.97_V1 2022-12-30 12-50-43".
> Done!
> ```

Awesome!

**Comment by orchetect** [comment]
I'm going to skip adding the CLI flag that would disable uniquing and error out of the process.

I'm sure that 99% of users & use cases will want automatic ID collision resolution. It's easy for users to spot this behavior and resolve their marker names after and re-run the CLI if needed.

We can always add the option later if there is a compelling need for it.
