### ISSUE TITLE
Tweaking Audio Roles Assignment for Titles & Video Generators 

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#91]
https://github.com/TheAcharya/MarkerData/issues/21#issuecomment-1916776555

After further tests, I realise that since, since we are assigning `Dialogue.Dialogue-1` to the `Title` Clips, we can't able to extract Marker on Titles without selecting `Dialogue.Dialogue-1` in our Roles Tab within Workflow Extension.

<img width="543" alt="Titles-Issue-01" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/0e686d97-c4a6-41bf-b224-620d7fc28f25">

After selecting `Title` and `Dialogue.Dialogue-1` I am able to extract just the Titles alone. 

<img width="374" alt="Titles-Issue-02" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/5b4ce1e1-db3a-4dc7-b94e-1757a74d794c">

User would not know to select `Dialogue.Dialogue-1` when selecting specific roles, since within FCP, Titles and Video Generators are not assigned with Audio Roles.

<img width="614" alt="Titles-Issue-03" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/a1ce1f2e-c26b-41ce-a81b-a0ca912a6150">

What is the best approach to solve this? Should we just keep the `Audio Role & Subrole` empty when there is no assign or not applicable?

**Comment by orchetect** [comment]
hmm. Yeah, in FCP it looks like Titles clips aren't even allowed to have an audio role selected, it just shows it blank and it's not selectable.

On reflection, this seems like it may be an oversight with the parsing. I'm not sure why it would want to put Dialog there. It would make sense to keep the audio role empty.

**Comment by orchetect** [comment]
I've made the necessary fix in DAWFileKit and will test MarkersExtractor to ensure correct behavior.

**Comment by orchetect** [comment]
Since MarkersExtractor replaces empty roles with "Not Assigned", that is what is now being output for Titles as its audio role. That should be fine, and seems consistent.

**Comment by IAmVigneswaran** [comment]
> Since MarkersExtractor replaces empty roles with "Not Assigned", that is what is now being output for Titles as its audio role. That should be fine, and seems consistent.

Yes, on our output payloads, we can print `Not Assigned` for Titles.

**Comment by IAmVigneswaran** [comment]
Just tested this! Seems to be working.
