### ISSUE TITLE
Thumbnails are still generated for profiles that don't support thumbnails

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/MarkersExtractor#93]
@orchetect When extracting for MIDI extract profile, the image data are also created. 

<img width="479" alt="MIDI-Bug" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/3346e855-85cd-48a4-902b-2589c8036e0a">

I have also tested with our CLI, directly. It does the same.

Is it possible not to include these files when extracting for MIDI profile.

Thank you.

**Comment by orchetect** [comment]
Just realized this is a broader issue. CSV and TSV also output thumbnail files too, not just with MIDI export.

**Comment by orchetect** [comment]
Fixed. Will be in 0.3.4.
