### ISSUE TITLE
Support for Standalone Clips (When Project Not Present)

### ISSUE THREAD

**Issue by samplue** [TheAcharya/MarkersExtractor#99]
One thing I'd love to see is  drag-n-drop support for compound clips. We edit scenes and entires reels in compound clips instead of projects. Unfortunately MarkerData will throw out an error. Copy pasting the timeline into a project works fine, but I'd love to avoid this extra step.

**Comment by IAmVigneswaran** [comment]
@orchetect Right now we are using `Project`'s FCPXML to perform extraction. 

Are we able to support Compound Clip's FCPXML? User's can also utilise Compound Clip for extraction.

<img width="435" alt="Compound-Clip" src="https://github.com/TheAcharya/MarkersExtractor/assets/118706051/2b0d6b34-93c6-4496-9558-260b0920af7b">

**Comment by orchetect** [comment]
Yeah that should be pretty straightforward.

IIRC, we're currently just taking the first project found in the FCPXML. Probably because that was the most common during our workflow and testing.

In later versions of the FCPXML format, it's possible to have a mixed variety of events, projects, and clips. For that reason I ensured the parser is already capable of finding them. It's just a matter of telling it what we want.

For MarkersExtractor, ideally it would autonomously determine its markers source based on what it finds in the FCPXML. I'd like to avoid having to require the user to tell it what the source is - and it may not be necessary any way for our needs.

I'm thinking the precedence for finding markers would be something like this:

1. If a project is found in the FCPXML, use that project. If more than one project is found, use the first.
2. Otherwise, check for a standalone clip. If more than one clip is found, use the first.

**Comment by IAmVigneswaran** [comment]
> 
> I'm thinking the precedence for finding markers would be something like this:
> 
> 1. If a project is found in the FCPXML, use that project. If more than one project is found, use the first.
> 2. Otherwise, check for a standalone clip. If more than one clip is found, use the first.

We can try this approach.

Thank you.

**Comment by orchetect** [comment]
This is actually a lot more involved than it may have seemed.

1. The notion of 'project' is pervasive in the source code so what I'm having to do is factor it out and replace it with the notion of a 'timeline'. That way a project or a clip or any conceivable timeline type can be used as the 'main timeline'. So it's involving code refactors but also changes to all the documentation to reflect that.
2. Some ancillary good news is that it's also led to some refactors of the parser that will make handling timelines better. The parser refactor

Parser updates are done. It's now a matter of refactoring and updating MarkersExtractor to use the new 'timeline' nomenclature and paradigm.

**Comment by IAmVigneswaran** [comment]
I will also update Marker Data's documentation site respectively; from `project` to `timeline`.

**Comment by orchetect** [comment]
Yes, and really we are only really dealing with a single timeline regardless of what timeline it is. To the users, we blur this line by now inferring the timeline from a project or a standalone clip, etc.

**Comment by orchetect** [comment]
When FCPXML only contains a clip, that means that our `Project Name` and `Library Name` manifest fields will be empty, since Final Cut does not export that data to the XML file in that case.

**Comment by orchetect** [comment]
> Are we able to support Compound Clip's FCPXML

Missed this question. Yes, dragging the clip directly from Final Cut Pro's browser will work. It creates intermediate FCPXML data containing just the clip. That's what I am using to unit test this as well.

**Comment by orchetect** [comment]
New alpha build for testing: https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.7-alpha1

**Comment by IAmVigneswaran** [comment]
Thanks for the new alpha build. Will report back soon!

**Comment by IAmVigneswaran** [comment]
On initial test, I get.

```
No timelines (projects or clips) could be found in the FCPXML.
Error: Error extracting timeline context.
```

This is a Compound Clip with first level clips.

[Marker Data Demo_V3 Clip CC.fcpxmld.zip](https://github.com/TheAcharya/MarkersExtractor/files/15376483/Marker.Data.Demo_V3.Clip.CC.fcpxmld.zip)

**Comment by orchetect** [comment]
How was this FCPXML exported?

**Comment by orchetect** [comment]
Ok, timeline parsing is more robust now and should work as expected.

Try alpha2: https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.7-alpha2

Also note: If it's a clip, MarkersExtractor will now use the clip name (and not project name) to:
- name the output folder
- used in filename ID if `timelineNameAndTimecode` ID naming mode is used (default, used to be `projectTimecode`)
- use it as default media base filename

**Comment by IAmVigneswaran** [comment]
Noted!

**Comment by orchetect** [comment]
Ok, timeline parsing is more robust now, and from my initial testing, it should work as expected.

Try alpha2: https://github.com/TheAcharya/MarkersExtractor/releases/tag/0.3.7-alpha2

**Comment by IAmVigneswaran** [comment]
Just did a quick test! Seems to be working as expected! Thank you, Steffan!

We can safely release 0.3.7?
